# <span style="color: #3498db;">2 Matrix Algebra</span>

What is Algebra?

代数：解方程

抽象的符号系统 + 线性运算规则 + 整体的空间结构

## 2.1 Matrix Operations(矩阵运算)
diagonal entries 对角线元素

main diagonal 主对角线

diagonal matrix 对角矩阵:n × n 矩阵，非对角线元素为0.

zero matrix 零矩阵：所有元素均为0；

### Sums and Scalar Multiples 加法和数乘

加法：相同大小矩阵对应元素相加

数乘：对应元素与标量相乘

#### Matrix Multiplication


  若线性变换依次由矩阵 $ B $ 和 $ A $ 作用，即 $ x \mapsto Bx \mapsto A(Bx) $，则此复合映射等价于**单个矩阵 $ AB $** 的作用，满足  
  $$
  A(Bx) = (AB)x.
  $$
  这里的 $ AB $ 称为 $ A $ 与 $ B $ 的乘积矩阵，它“合成”了两次线性变换。

  设 $ A $ 为 $ m \times n $，$ B $ 为 $ n \times p $，$ x \in \mathbb{R}^p $。
  将 $ B $ 的列向量记为 $ \mathbf{b}_1, \dots, \mathbf{b}_p $，$ x $ 的分量记为 $ x_1, \dots, x_p $，则  
  $$
  Bx = x_1\mathbf{b}_1 + x_2\mathbf{b}_2 + \cdots + x_p\mathbf{b}_p.
  $$
  由于矩阵乘法 $ A(\cdot) $ 是线性映射，因此  
  $$
  A(Bx) = A\left(\sum_{j=1}^p x_j \mathbf{b}_j\right) = \sum_{j=1}^p x_j (A\mathbf{b}_j).
  $$
  若定义矩阵 $ AB $ 的列向量为 $ A\mathbf{b}_1, A\mathbf{b}_2, \dots, A\mathbf{b}_p $，则上式恰好等于 $ (AB)x $。故  
  $$
  (AB)x = \sum_{j=1}^p x_j (A\mathbf{b}_j),
  $$
  从而验证了 $ A(Bx) = (AB)x $。

#### 几何意义
  先做 $ B $ 对应的线性变换，再做 $ A $ 对应的线性变换，等价于直接做 $ AB $ 对应的线性变换。

  该结论是线性代数中**矩阵乘法定义**的动机之一，也体现了线性变换复合与矩阵乘积的一致性。

#### 适用范围
  矩阵乘法 $ AB $ 有定义当且仅当 $ A $ 的列数等于 $ B $ 的行数（均为 $ n $），结果矩阵为 $ m \times p $。  
  对任意 $ x \in \mathbb{R}^p $，上式恒成立，因此复合映射的矩阵表示唯一确定。


**关键公式**  
$$
\boxed{A(Bx) = (AB)x}
$$  
其中 $ AB $ 的第 $ j $ 列为 $ A\mathbf{b}_j $。 

$ AB $ 的每一列相当于$ A $ 的 列向量的线性组合，系数为B的对应列。

#### 矩阵乘法：行‑列法则（Row‑Column Rule for Computing $AB$）
若矩阵乘积 $AB$ 有定义，则乘积矩阵 $AB$ 的第 $i$ 行第 $j$ 列元素，等于$A$ 的第 $i$ 行与$B$ 的第 $j$ 列对应位置元素相乘之后求和。

设 $A$ 是 $m\times n$ 矩阵，$(AB)_{ij}$ 代表矩阵 $AB$ 的 $(i,j)$ 位置元素：
$$
(AB)_{ij}=a_{i1}b_{1j}+a_{i2}b_{2j}+\dots+a_{in}b_{nj}
$$

> 要点：
> 1. 只有 $A$ 的列数 = $B$ 的行数，$AB$ 才可以相乘；
> 2. 取 $A$ 的第 $i$ 行，$B$ 的第 $j$ 列，对应相乘再相加，得到结果矩阵的 $(i,j)$ 元。



### Properties of Matrix Multiplication

![2-1.png](picture/chapter_2_picture/2-1.png)


AB:  B由A左乘

若AB = BA，称A和B可以互换（commute）


### Powers of a Matrix 矩阵的幂运算

$A$ 必须是 $n\times n$ 方阵，$k$ 为正整数：

$$
A^k=\underbrace{A\,A\cdots A}_{k\text{ 个}A}
$$

$A^k$ 表示 $k$ 个方阵 $A$ 连续相乘。

- 设向量 $\boldsymbol x\in \mathbb R^n$，则 $A^k\boldsymbol x$：对向量 $\boldsymbol x$ 重复左乘矩阵 $A$，一共执行 $k$ 次。
- 零次幂定义：$A^0 = I$，$I$ 为单位矩阵，满足 $A^0\boldsymbol x=\boldsymbol x$。

> 注意：矩阵幂**仅对方阵有定义**，广泛用于理论推导和工程应用。


### The Transpose of a Matrix

给定 $m\times n$ 矩阵 $A$，$A$ 的**转置**记作 $A^T$，是一个 $n\times m$ 矩阵。
$A^T$ 的列由原矩阵 $A$ 对应的行构成。

#### 转置的性质
设矩阵 $A,B$ 的维度满足运算要求：

a. $(A^T)^T = A$

b. $(A+B)^T = A^T + B^T$

c. 对任意标量 $r$，$(rA)^T = rA^T$

d. $(AB)^T = B^T A^T$

> 一般 $(AB)^T \neq A^T B^T$，即使 $A^T B^T$可以计算。

> 多个矩阵乘积的转置：
> **矩阵乘积的转置，等于各个矩阵转置之后，顺序颠倒再相乘。**


### 练习2.1 33
![2-2.png](picture/chapter_2_picture/2-2.png)

**证明**：

 先证 $C=D$。  
   考虑乘积 $CAD$。利用结合律：
   $$
   CAD = (CA)D = I_n D = D,
   $$
   同时
   $$
   CAD = C(AD) = C I_m = C.
   $$
   因此 $C=D$。

 再证 $m=n$。 
   由 $AD=I_m$，两边取秩：
   $$
   m = \operatorname{rank}(I_m) = \operatorname{rank}(AD) \le \operatorname{rank}(A) \le \min(m,n).
   $$
   所以 $m \le \min(m,n)$，这推出 $m \le n$。  
   同理，由 $CA=I_n$，
   $$
   n = \operatorname{rank}(I_n) = \operatorname{rank}(CA) \le \operatorname{rank}(A) \le \min(m,n),
   $$
   所以 $n \le \min(m,n)$，推出 $n \le m$。  
   综上 $m=n$。

因此结论成立：$m=n$ 且 $C=D$。

### 练习2.1 33
![2-3.png](picture/chapter_2_picture/2-3.png)

In [43]:
import numpy as np

# 定义矩阵 A
A = np.array([
    [1/6, 1/2, 1/3],
    [1/2, 1/4, 1/4],
    [1/3, 1/4, 5/12]
])

# 计算并打印各次幂
powers = [5, 10, 20, 30]
for p in powers:
    Ap = np.linalg.matrix_power(A, p)
    print(f"A^{p} =\n", Ap, "\n")


A^5 =
 [[0.33182227 0.33458719 0.33359053]
 [0.33458719 0.3323206  0.33309221]
 [0.33359053 0.33309221 0.33331726]] 

A^10 =
 [[0.33333725 0.33333011 0.33333264]
 [0.33333011 0.33333599 0.3333339 ]
 [0.33333264 0.3333339  0.33333346]] 

A^20 =
 [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]] 

A^30 =
 [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]] 



当指数增加时，结果趋向于一个相同的矩阵，每一列都变成了同一个列向量，这相当于特征值为1时的特征向量，类似于第一章中的1.10 13.


### 练习2.1 49
![2-4.png](picture/chapter_2_picture/2-4.png)
![2-5.png](picture/chapter_2_picture/2-5.png)

In [44]:
# 定义矩阵 M
M = np.array([
    [1, 0, -1, 0],
    [0, 1,  0, 0],
    [-1, 0, 1, 0],
    [0, 0,  0, 1]
])

print("矩阵 M：")
print(M)

# 遍历所有 16 个可能的 4 位二进制数
for i in range(16):
    # 将整数 i 转为 4 位二进制字符串，再转为整数列表（0/1）
    bits = [int(b) for b in format(i, '04b')]
    x = np.array(bits).reshape(4, 1)  # 列向量
    
    # 跳过零向量
    if np.all(x == 0):
        continue
    
    # 计算二次型 x^T M x （结果是一个 1x1 矩阵，取标量）
    value = (x.T @ M @ x)[0, 0]
    
    # 由于浮点运算，判断是否接近 0（容忍极小误差）
    if abs(value) < 1e-12:
        # 将 x 重塑为 2x2 图案
        # 约定：x1 x2 为第一列，x3 x4 为第二列
        pattern = np.array(bits).reshape(2, 2).T
        print(f"找到 x = {bits}")
        print("对应的 2x2 图案：")
        print(pattern)

矩阵 M：
[[ 1  0 -1  0]
 [ 0  1  0  0]
 [-1  0  1  0]
 [ 0  0  0  1]]
找到 x = [1, 0, 1, 0]
对应的 2x2 图案：
[[1 1]
 [0 0]]


### 练习2.1 50
![2-6.png](picture/chapter_2_picture/2-6.png)

In [45]:
# 定义矩阵 M
M = np.array([
    [1, 0, 0, -1],
    [0, 1,  0, -1],
    [0, 0, 1, 0],
    [-1, -1, 0, 2]
])

print("矩阵 M：")
print(M)

# 遍历所有 16 个可能的 4 位二进制数
for i in range(16):
    # 将整数 i 转为 4 位二进制字符串，再转为整数列表（0/1）
    bits = [int(b) for b in format(i, '04b')]
    x = np.array(bits).reshape(4, 1)  # 列向量
    
    # 跳过零向量
    if np.all(x == 0):
        continue
    
    # 计算二次型 x^T M x （结果是一个 1x1 矩阵，取标量）
    value = (x.T @ M @ x)[0, 0]
    
    # 由于浮点运算，判断是否接近 0（容忍极小误差）
    if abs(value) < 1e-12:
        # 将 x 重塑为 2x2 图案
        # 约定：x1 x2 为第一列，x3 x4 为第二列
        pattern = np.array(bits).reshape(2, 2).T
        print(f"找到 x = {bits}")
        print("对应的 2x2 图案：")
        print(pattern)

矩阵 M：
[[ 1  0  0 -1]
 [ 0  1  0 -1]
 [ 0  0  1  0]
 [-1 -1  0  2]]
找到 x = [1, 1, 0, 1]
对应的 2x2 图案：
[[1 0]
 [1 1]]


### 练习2.1 51
![2-7.png](picture/chapter_2_picture/2-7.png)

In [46]:
# 定义矩阵 A（交换行）
A = np.array([
    [0, 1],
    [1, 0]
])

# 定义矩阵 M（原始数据）
M = np.array([
    [2, 3, 16, 24, 25, 26, 6, 7, 19, 26],
    [1, 1,  1,  1,  1,  1, 2, 2,  2,  2]
])

# 计算 AM（左乘）
AM = A @ M
print("\n交换后的矩阵 AM = A × M：")
print(AM)


交换后的矩阵 AM = A × M：
[[ 1  1  1  1  1  1  2  2  2  2]
 [ 2  3 16 24 25 26  6  7 19 26]]


### 练习2.1 52
![2-8.png](picture/chapter_2_picture/2-8.png)

In [47]:
# 定义矩阵 B
B = np.array([
    [1, 0, 0],
    [0, 1, 0]
])

# 定义矩阵 N
N = np.array([
    [1,    1,    1,    1,    2,    2,    2],
    [1,   12,   21,   22,    3,   20,   21],
    [2020, 2020, 2020, 2020, 2020, 2020, 2020]
])

# 计算 BN
BN = B @ N
print("\n删除最后一行后的 BN = B × N：")
print(BN)


删除最后一行后的 BN = B × N：
[[ 1  1  1  1  2  2  2]
 [ 1 12 21 22  3 20 21]]


以上例题（51/52）总结，A左乘M相当于是对M进行行变换，左乘本质上就是在“混合/挑选/交换”原矩阵的行。

## 2.2 The Inverse of a Matrix 矩阵的逆

inverse 逆的，相反的，逆元素

**矩阵逆的定义**
- 对于一个 $n \times n$ 的方阵 $A$，如果存在一个 $n \times n$ 矩阵 $C$，使得：
  $$CA = I_n \quad \text{且} \quad AC = I_n$$
  其中 $I_n$ 是 $n$ 阶单位矩阵，则称 $A$ 是**可逆的（invertible）**，$C$ 称为 $A$ 的一个**逆矩阵（inverse）**。

- **注意**：由于矩阵乘法不满足交换律，必须同时满足两个等式（左逆和右逆）。

**逆矩阵的唯一性**
- 如果 $B$ 也是 $A$ 的逆矩阵，则：
  $$B = BI = B(AC) = (BA)C = IC = C$$
  因此逆矩阵是唯一的，记为 $A^{-1}$。

- 于是有：
  $$A^{-1}A = I, \quad AA^{-1} = I$$

- **可逆矩阵（invertible matrix）** 也称为**非奇异矩阵（nonsingular matrix）**。
- **不可逆矩阵** 称为**奇异矩阵（singular matrix）**。

- 只有**方阵**才可能具有逆矩阵（非方阵没有通常意义下的逆）。
- 求逆矩阵的方法包括伴随矩阵法、高斯-约当消元法等。

**2x2 矩阵的行列式（Determinant）**

对于矩阵 $A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$，其行列式定义为：
$$\det A = ad - bc$$

**可逆性条件与逆矩阵公式**
- 如果 $\det A = ad - bc \neq 0$，则 $A$ 是可逆的（非奇异），其逆矩阵为：
$$A^{-1} = \frac{1}{ad - bc} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$$

- 如果 $\det A = ad - bc = 0$，则 $A$ 不可逆（奇异）。

> **核心结论**：一个 $2\times2$ 矩阵 $A$ 可逆 **当且仅当** $\det A \neq 0$。

**可逆矩阵的重要定理**
如果 $A$ 是一个可逆的 $n \times n$ 矩阵，那么对于 $\mathbb{R}^n$ 中的任意向量 $\mathbf{b}$，方程：
$$A\mathbf{x} = \mathbf{b}$$
总有**唯一解**，且该解为：
$$\mathbf{x} = A^{-1}\mathbf{b}$$

### 直观理解
逆矩阵能快速解开线性方程组 $A\mathbf{x} = \mathbf{b}$。只要算出 $A^{-1}$，直接左乘 $\mathbf{b}$ 就能得到解，避免了繁琐的高斯消元过程。



### 逆矩阵的基本性质
- **(a) 逆的逆**：若 $A$ 可逆，则 $A^{-1}$ 也可逆，并且：
  $$(A^{-1})^{-1} = A$$

- **(b) 乘积的逆（反向顺序）**：若 $A$ 和 $B$ 都是 $n\times n$ 可逆矩阵，则它们的乘积 $AB$ 也可逆，且：
  $$(AB)^{-1} = B^{-1}A^{-1}$$
  


- **(c) 转置的逆**：若 $A$ 可逆，则 $A^T$ 也可逆，且：
  $$(A^T)^{-1} = (A^{-1})^T$$
  即“转置”与“求逆”这两个运算可交换顺序。

### 推广到多个矩阵
对于多个可逆矩阵的乘积，逆矩阵仍然是各自逆矩阵的乘积，但顺序完全颠倒：
$$(A_1 A_2 \cdots A_k)^{-1} = A_k^{-1} \cdots A_2^{-1} A_1^{-1}$$


### 计算方法：行操作与逆矩阵
可逆矩阵 $A$ 与单位矩阵 $I$ **行等价**（即可以通过若干初等行变换将 $A$ 变成 $I$）。我们可以利用这一性质来求 $A^{-1}$：

- 将矩阵 $A$ 与单位矩阵 $I$ 并排组成增广矩阵 $[A \mid I]$。
- 对该增广矩阵进行初等行变换，直到左侧变成 $I$。
- 此时，右侧就变成了 $A^{-1}$，即：
$$[A \mid I] \sim [I \mid A^{-1}]$$



### Elementary Matrices 初等矩阵

#### 1. 初等矩阵的定义
**初等矩阵** 是对**单位矩阵**执行一次**初等行变换**所得到的矩阵。

#### 2. 核心性质：左乘 = 行变换
对于一个 $m \times n$ 矩阵 $A$，**左乘**一个初等矩阵 $E$，等价于对 $A$ 执行**对应的行变换**：

$$EA = \text{对 } A \text{ 执行该行变换后的结果}$$


#### 3. 初等矩阵的可逆性
**每个初等矩阵都可逆**，且其逆矩阵仍为同类型的初等矩阵，作用是将该行变换“撤销”：

- $E_1$（行替换）的逆：把加上的倍数再减回去。  
  例如：$E_1 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ -4 & 0 & 1 \end{bmatrix}$，其逆为 $E_1^{-1} = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 4 & 0 & 1 \end{bmatrix}$。

- $E_2$（行交换）的逆：交换两次等于没变，所以 $E_2^{-1} = E_2$。

- $E_3$（行倍乘）的逆：乘以倒数，即 $\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1/5 \end{bmatrix}$。


#### 4. 定理7：可逆矩阵与行等价
> **核心定理**：一个 $n \times n$ 矩阵 $A$ 可逆，**当且仅当** $A$ 行等价于单位矩阵 $I_n$（即 $A \sim I_n$）。

##### 推论（求逆矩阵的方法）
若 $A \sim I_n$，则**把 $A$ 化成 $I_n$ 的同一系列初等行变换**，也同时把 $I_n$ 变成 $A^{-1}$。

实际操作（高斯-约当消元法）：
1. 构造增广矩阵 $[A \mid I]$。
2. 对 $[A \mid I]$ 进行行变换，直到左侧变成 $I$。
3. 此时右侧自动变为 $A^{-1}$。


#### 6. 关于“当且仅当”与“conversely”
- **“$P$ 当且仅当 $Q$”** 等价于两个方向：
  1. 若 $P$ 则 $Q$（充分性）
  2. 若 $Q$ 则 $P$（必要性，即“反之”）



#### 7. 总结：初等矩阵与逆矩阵的关系
| 概念 | 说明 |
| :--- | :--- |
| 初等矩阵 | 单位矩阵经一次行变换得到 |
| 左乘初等矩阵 | 对原矩阵执行对应的行变换 |
| 初等矩阵的逆 | 撤销该行变换的初等矩阵 |
| 可逆矩阵 | 可分解为一系列初等矩阵的乘积 |
| 求逆方法 | 用行变换将 $[A \mid I]$ 化为 $[I \mid A^{-1}]$ |
```

#### 矩阵求逆的另一种视角：列观点与数值考量

**列观点：将逆矩阵视为多个线性方程组的解**
设单位矩阵 $I_n$ 的列为 $\mathbf{e}_1, \mathbf{e}_2, \ldots, \mathbf{e}_n$，其中：
$$\mathbf{e}_1 = \begin{bmatrix} 1 \\ 0 \\ \vdots \\ 0 \end{bmatrix}, \quad \mathbf{e}_2 = \begin{bmatrix} 0 \\ 1 \\ \vdots \\ 0 \end{bmatrix}, \quad \ldots, \quad \mathbf{e}_n = \begin{bmatrix} 0 \\ 0 \\ \vdots \\ 1 \end{bmatrix}$$

则求解 $A^{-1}$ 等价于**同时求解以下 $n$ 个线性方程组**：
$$A\mathbf{x} = \mathbf{e}_1, \quad A\mathbf{x} = \mathbf{e}_2, \quad \ldots, \quad A\mathbf{x} = \mathbf{e}_n$$

将所有这些方程组的增广列并排放在一起，就得到：
$$[A \mid \mathbf{e}_1 \ \mathbf{e}_2 \ \cdots \ \mathbf{e}_n] = [A \mid I_n]$$

对其进行行化简，直到左侧变为 $I_n$ 时，右侧自动变为 $A^{-1}$：
$$[A \mid I_n] \sim [I_n \mid A^{-1}]$$

**直观理解**
- 逆矩阵的**第 $j$ 列**，就是方程组 $A\mathbf{x} = \mathbf{e}_j$ 的唯一解。
- 也就是说，$A^{-1}$ 的每一列都在回答一个问题：**“哪个向量 $\mathbf{x}$ 会被 $A$ 映射到第 $j$ 个标准基向量？”**


#### 数学推导验证
设 $A^{-1} = \begin{bmatrix} \mathbf{x}_1 & \mathbf{x}_2 & \cdots & \mathbf{x}_n \end{bmatrix}$（$\mathbf{x}_j$ 为第 $j$ 列），则由 $A A^{-1} = I$ 可得：
$$A\mathbf{x}_j = \mathbf{e}_j, \quad j = 1, 2, \ldots, n$$

因此，**求逆矩阵本质上就是求解 $n$ 个具有相同系数矩阵 $A$、不同右侧向量的线性方程组**。


**数值提示**
在实际计算中：

- **很少真正计算 $A^{-1}$**，除非确实需要逆矩阵的**所有元素**（例如用于理论推导或某些特定算法）。
- 计算 $A^{-1}$ 再乘以 $\mathbf{b}$（即 $A^{-1}\mathbf{b}$），其算术运算量大约是**直接对 $A\mathbf{x} = \mathbf{b}$ 做行化简（高斯消元）的 3 倍**。
- 此外，直接行化简通常**数值稳定性更好**，误差更小。

#### 结论
> 在绝大多数应用中，**求解线性方程组应直接使用行化简（高斯消元或 LU 分解），而不是先求逆再乘**。只有当你需要多次求解同一个 $A$ 但不同 $\mathbf{b}$ 的方程组时，先求逆才可能效率更高（但更稳定做法是计算 $A$ 的 LU 分解或保存增广矩阵行化简结果）。


#### 总结对比

| 方法 | 原理 | 适用场景 | 运算量 | 数值稳定性 |
| :--- | :--- | :--- | :--- | :--- |
| 直接行化简（高斯消元） | 将 $[A \mid \mathbf{b}]$ 化为行阶梯形 | 求解单个或少量右侧向量 | 较少 | 较好 |
| 先求逆再乘（$A^{-1}\mathbf{b}$） | 计算 $A^{-1}$ 后乘以 $\mathbf{b}$ | 需要逆矩阵的全部元素，或需要反复求解同一 $A$ 的多个 $\mathbf{b}$ | 约为行化简的 3 倍 | 通常较差 |

### 练习2.2 46
![2-9.png](picture/chapter_2_picture/2-9.png)

In [48]:
# 定义矩阵 A
A = np.array([
    [-25, -9, -27],
    [546, 180, 537],
    [154, 50, 149]
])

# 单位矩阵的第2列和第3列（标准基向量）
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])

# 求解 A * x = e2 和 A * x = e3
# 得到的 x 就是 A^{-1} 的第2列和第3列（因为 A^{-1} 的第j列是方程 A x = e_j 的解）
col2 = np.linalg.solve(A, e2)
col3 = np.linalg.solve(A, e3)

print("A^{-1} 的第二列：", col2)
print("A^{-1} 的第三列：", col3)

# 验证
print("\n验证：A * col2 =", A @ col2)  # 应该等于 [0,1,0]
print("验证：A * col3 =", A @ col3)  # 应该等于 [0,0,1]

A^{-1} 的第二列： [  1.5        -72.16666667  22.66666667]
A^{-1} 的第三列： [ -4.5 219.5 -69. ]

验证：A * col2 = [0. 1. 0.]
验证：A * col3 = [0. 0. 1.]


## 2.3 Characterizations of Invertible Matrices 可逆矩阵的特性

#### 1. 可逆矩阵定理（The Invertible Matrix Theorem）
设 $A$ 是 $n\times n$ 方阵，则以下命题**等价**（对于给定的 $A$，它们要么全真，要么全假）：

a. **$A$ 是可逆矩阵**（存在 $A^{-1}$）。  
b. $A$ 行等价于 $I_n$（$A \sim I_n$）。  
c. $A$ 有 $n$ 个主元位置。  
d. 方程 $A\mathbf{x} = \mathbf{0}$ **只有平凡解** $\mathbf{x} = \mathbf{0}$。  
e. $A$ 的列向量构成**线性无关**集合。  
f. 线性变换 $\mathbf{x} \mapsto A\mathbf{x}$ 是**单射（one-to-one）**。  
g. 对 $\mathbb{R}^n$ 中任意 $\mathbf{b}$，方程 $A\mathbf{x} = \mathbf{b}$ **至少有一个解**。  
h. $A$ 的列向量**张成** $\mathbb{R}^n$（span $\mathbb{R}^n$）。  
i. 线性变换 $\mathbf{x} \mapsto A\mathbf{x}$ 是**满射（onto）** $\mathbb{R}^n$。  
j. 存在 $n\times n$ 矩阵 $C$，使得 $CA = I$。  
k. 存在 $n\times n$ 矩阵 $D$，使得 $AD = I$。  
l. $A^T$ 是可逆矩阵。

> **核心意义**：这 12 个命题从线性方程组、线性代数、线性变换、矩阵运算等多个角度描述了“可逆”这一性质，它们完全等价。




#### 2. 定理证明思路（“循环蕴含”）
证明通过建立以下蕴含循环来完成：
$$(a) \Rightarrow (j) \Rightarrow (d) \Rightarrow (c) \Rightarrow (b) \Rightarrow (a)$$

- **(a) ⇒ (j)**：显然，取 $C = A^{-1}$ 即可。
- **(j) ⇒ (d)**：若 $CA = I$，且 $A\mathbf{x} = \mathbf{0}$，则 $CA\mathbf{x} = C\mathbf{0}$ ⇒ $\mathbf{x} = \mathbf{0}$，所以只有平凡解。
- **(d) ⇒ (c)**：若只有平凡解，则 $A$ 的每一列都有主元（无自由变量），因为 $A$ 是方阵，所以主元个数为 $n$。
- **(c) ⇒ (b)**：$n$ 个主元在 $n\times n$ 矩阵中必须位于主对角线，因此行最简形为 $I_n$。
- **(b) ⇒ (a)**：由定理 7（初等矩阵与逆矩阵），$A \sim I_n$ 意味着 $A$ 可逆。

然后分别将其他命题也连接进来：
- **(a) ⇒ (k)**：$D = A^{-1}$ 使 $AD = I$。
- **(k) ⇒ (g)**：若 $AD = I$，则对任意 $\mathbf{b}$，$\mathbf{x} = D\mathbf{b}$ 是 $A\mathbf{x} = \mathbf{b}$ 的一个解。
- **(g) ⇒ (a)**：可由习题 34（2.2 节）证明。

同时，对于任意矩阵（不一定方阵），有：
- **(g)、(h)、(i) 等价**（定理 4 in §1.4 和定理 12(a) in §1.9）。
- **(d)、(e)、(f) 等价**（§1.7 和定理 12(b) in §1.9）。

最后：
- **(a) ⇒ (l)**：由 $(A^T)^{-1} = (A^{-1})^T$（定理 6(c)）可得；反之 **(l) ⇒ (a)** 同理，只需把 $A$ 与 $A^T$ 互换。



#### 3. 重要推论
> 若 $A$ 和 $B$ 是方阵且 $AB = I$，则 $A$ 和 $B$ 都可逆，且 $B = A^{-1}$，$A = B^{-1}$。

这由可逆矩阵定理的 (j) 与 (k) 结合即可推出。


#### 4. 矩阵分类
- **可逆矩阵（非奇异 Nonsingular）**：满足上述任意一条。
- **不可逆矩阵（奇异 Singular）**：不满足上述任意一条（例如：行最简形不是 $I$，无 $n$ 个主元，列线性相关等）。


#### 5. 可逆线性变换（Invertible Linear Transformations）
设 $T: \mathbb{R}^n \to \mathbb{R}^n$ 是线性变换，其标准矩阵为 $A$。若存在 $S: \mathbb{R}^n \to \mathbb{R}^n$ 使得：
$$S(T(\mathbf{x})) = \mathbf{x} \quad \text{且} \quad T(S(\mathbf{x})) = \mathbf{x}$$
则称 $T$ 可逆，$S$ 为 $T$ 的逆，记为 $T^{-1}$。

**定理 9**
$T$ 可逆 $\iff$ $A$ 可逆。此时 $T^{-1}$ 是线性变换，且其标准矩阵为 $A^{-1}$，即 $T^{-1}(\mathbf{x}) = A^{-1}\mathbf{x}$。


#### 6. 数值计算注意事项（Numerical Notes）
在实际数值计算中：
- **病态矩阵（Ill-conditioned matrix）**：可逆但“几乎奇异”，微小扰动可使行列式接近零或变成奇异。
- **舍入误差（Roundoff error）**：
  - 对病态矩阵进行行化简，可能因舍入误差导致主元数量少于 $n$。
  - 也可能使一个奇异矩阵被误判为可逆。
- **条件数（Condition Number）**：
  - 矩阵程序常计算条件数，值越大，矩阵越接近奇异。
  - 单位矩阵的条件数为 1；奇异矩阵的条件数为无穷大。
  - 条件数很大时，矩阵计算可能产生显著误差。



**矩阵的条件数（Condition Number）**

**什么是条件数？**
条件数（记为 $\kappa(A)$）是衡量一个矩阵 **“对误差的敏感程度”** 的指标。在数值计算中，它决定了当输入数据（矩阵 $A$ 或向量 $b$）发生微小扰动时，方程 $A\mathbf{x} = \mathbf{b}$ 的解 $\mathbf{x}$ 会被放大多少倍。

**数学定义**
对于可逆矩阵 $A$，其条件数定义为：
$$\kappa(A) = \|A\| \cdot \|A^{-1}\|$$
其中 $\| \cdot \|$ 表示矩阵的某种范数（可以通俗理解为矩阵的“大小”或“长度”）。

**数值范围与含义**
- **最小值 $= 1$**：矩阵“极其健康”，对误差完全不敏感。  
  例子：单位矩阵 $I$ 的条件数恰好是 $1$。
- **数值越大**：矩阵越“病态”（Ill-conditioned），对误差越敏感。
- **无穷大（$\infty$）**：矩阵是**奇异矩阵（不可逆）**。


**与可逆性、数值计算的关系**
- 奇异矩阵（不可逆）的条件数是**无穷大**。
- 病态矩阵在数学上是可逆的（行列式不为零），但在计算机浮点数运算中，微小的舍入误差就可能让它“看起来像”奇异矩阵。
- 如果条件数极大（例如 $10^{12}$），计算机程序可能**无法区分**它和真正的奇异矩阵，此时计算出的逆矩阵或方程解可能完全不可信。



#### 8. 总结：可逆矩阵
| 角度 | 等价描述 |
| :--- | :--- |
| 代数 | 存在逆矩阵 $A^{-1}$ |
| 行操作 | 行等价于 $I_n$，有 $n$ 个主元 |
| 线性方程组 | $A\mathbf{x}=\mathbf{0}$ 只有零解；$A\mathbf{x}=\mathbf{b}$ 对任意 $\mathbf{b}$ 有（唯一）解 |
| 列向量 | 线性无关，张成 $\mathbb{R}^n$ |
| 线性变换 | 单射且满射（双射），即存在逆变换 |
| 矩阵乘法 | 存在 $C$ 使 $CA=I$ 或 $AD=I$ |
| 转置 | $A^T$ 也可逆 |


### 练习2.3 9-10
![2-10.png](picture/chapter_2_picture/2-10.png)
![2-11.png](picture/chapter_2_picture/2-11.png)

In [49]:
# 矩阵9
A9 = np.array([
    [4, 0, -7, -7],
    [-6, 1, 11, 9],
    [7, -5, 10, 19],
    [-1, 2, 3, -1]
])

# 矩阵10
A10 = np.array([
    [5, 3, 1, 7, 9],
    [6, 4, 2, 8, -8],
    [7, 5, 3, 10, 9],
    [9, 6, 4, -9, -5],
    [8, 5, 2, 11, 4]
])

det9 = np.linalg.det(A9)
det10 = np.linalg.det(A10)

print(f"矩阵9的行列式 = {det9}")
print(f"矩阵10的行列式 = {det10}")

tol = 1e-12
if abs(det9) < tol:
    print("矩阵9不可逆（奇异）")
else:
    print("矩阵9可逆（非奇异）")

if abs(det10) < tol:
    print("矩阵10不可逆（奇异）")
else:
    print("矩阵10可逆（非奇异）")

矩阵9的行列式 = 1.000000000000334
矩阵10的行列式 = 1.9999999999994091
矩阵9可逆（非奇异）
矩阵10可逆（非奇异）


### 练习2.3 50-51
![2-12.png](picture/chapter_2_picture/2-12.png)

In [50]:
np.random.seed(2026)

# 矩阵 A（来自练习 9）
A9 = np.array([
    [4, 0, -7, -7],
    [-6, 1, 11, 9],
    [7, -5, 10, 19],
    [-1, 2, 3, -1]
])

# 条件数
cond9 = np.linalg.cond(A9, p=2)
print(f"练习 50: 矩阵 A9 的条件数 = {cond9:.6f}")

# 随机生成精确解 x
x = np.random.randn(4)
b = A9 @ x

# 求解 Ax = b
x1 = np.linalg.solve(A9, b)

# 相对误差
rel_err = np.linalg.norm(x1 - x, 2) / np.linalg.norm(x, 2)
print(f"相对误差 = {rel_err:.4e}")

# 机器精度
eps = np.finfo(float).eps
machine_digits = -np.log10(eps)
print(f"机器精度约 {machine_digits:.0f} 位十进制有效数字")

# 实际有效位数
if rel_err > 0:
    actual_digits = -np.log10(rel_err)
    lost = machine_digits - actual_digits
    print(f"实际 x 与 x1 一致的位数约 {actual_digits:.0f} 位，丢失精度约 {lost:.0f} 位")
else:
    print("完全精确")

练习 50: 矩阵 A9 的条件数 = 23682.927875
相对误差 = 2.9190e-13
机器精度约 16 位十进制有效数字
实际 x 与 x1 一致的位数约 13 位，丢失精度约 3 位


In [51]:
# 矩阵 A10（来自练习 10）
A10 = np.array([
    [5, 3, 1, 7, 9],
    [6, 4, 2, 8, -8],
    [7, 5, 3, 10, 9],
    [9, 6, 4, -9, -5],
    [8, 5, 2, 11, 4]
])

# 条件数
cond10 = np.linalg.cond(A10, p=2)
print(f"\n练习 51: 矩阵 A10 的条件数 = {cond10:.4e}")

# 随机生成精确解 x（5维）
x = np.random.randn(5)
b = A10 @ x

# 求解
x1 = np.linalg.solve(A10, b)

# 相对误差
rel_err = np.linalg.norm(x1 - x, 2) / np.linalg.norm(x, 2)
print(f"相对误差 = {rel_err:.4e}")

if rel_err > 0:
    actual_digits = -np.log10(rel_err)
    lost = machine_digits - actual_digits
    print(f"实际一致的位数约 {actual_digits:.0f} 位，丢失精度约 {lost:.0f} 位")
else:
    print("完全精确")


练习 51: 矩阵 A10 的条件数 = 6.8622e+04
相对误差 = 1.9495e-12
实际一致的位数约 12 位，丢失精度约 4 位


### 练习2.3 52
![2-13.png](picture/chapter_2_picture/2-13.png)

In [52]:
# 构造 5×5 希尔伯特矩阵
n = 5
H = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        H[i, j] = 1 / (i + j + 1)   # i,j 从0开始

# 单位矩阵第 5 列（最后一列）
e5 = np.zeros(n)
e5[-1] = 1

# 求解 H x = e5，得到逆矩阵最后一列
x_col5 = np.linalg.solve(H, e5)

# 精确解（题目给出）
exact = np.array([630, -12600, 56700, -88200, 44100])

print("数值解:", x_col5)
print("精确解:", exact)

# 误差
err = np.abs(x_col5 - exact)
print("绝对误差:", err)

# 预期正确位数（近似）
if np.all(err > 0):
    rel_err_col = np.linalg.norm(err) / np.linalg.norm(exact)
    correct_digits = -np.log10(rel_err_col)
    print(f"相对误差 = {rel_err_col:.4e}，预期正确位数约 {correct_digits:.0f} 位")

数值解: [   630.         -12599.99999999  56699.99999995 -88199.99999994
  44099.99999997]
精确解: [   630 -12600  56700 -88200  44100]
绝对误差: [7.26686267e-10 1.17070158e-08 4.55329427e-08 6.36791810e-08
 2.93439371e-08]
相对误差 = 7.3764e-13，预期正确位数约 12 位


### 练习2.3 53
![2-14.png](picture/chapter_2_picture/2-14.png)

In [53]:
import numpy as np

def hilbert(n):
    """生成 n 阶希尔伯特矩阵"""
    return np.array([[1 / (i + j + 1) for j in range(n)] for i in range(n)])

def test_hilbert_inverse(order):
    """测试指定阶数的希尔伯特矩阵求逆与验证"""
    print(f"希尔伯特矩阵阶数: n = {order}")
    
    A = hilbert(order)
    
    #  计算条件数
    cond = np.linalg.cond(A, p=2)
    print(f"条件数 (2-范数) = {cond:.4e}")
    
    #  尝试求逆
    try:
        invA = np.linalg.inv(A)
    except np.linalg.LinAlgError:
        print("!!! 矩阵被判定为奇异，无法求逆（数值上已不可逆）")
        return
    
    #  计算 AA^{-1}
    I_calc = A @ invA
    I_eye = np.eye(order)
    
    #  计算与单位矩阵的差异（使用 Frobenius 范数）
    error_fro = np.linalg.norm(I_calc - I_eye, 'fro')
    print(f"AA^(-1) 与 I 的 Frobenius 范数误差: {error_fro:.4e}")
    
    #  直观判断可靠性
    if error_fro > 1e-2:
        print("结论：AA^(-1) 非单位矩阵,逆矩阵已经完全不可靠。")
    elif error_fro > 1e-6:
        print("结论：AA^(-1) 有明显偏差，逆矩阵存在较大数值误差。")
    else:
        print("结论：数值结果基本可信。")

# 从 5 阶到 14 阶
for n in [5, 10, 12, 14]:
    test_hilbert_inverse(n)
    print()  

希尔伯特矩阵阶数: n = 5
条件数 (2-范数) = 4.7661e+05
AA^(-1) 与 I 的 Frobenius 范数误差: 3.8740e-12
结论：数值结果基本可信。

希尔伯特矩阵阶数: n = 10
条件数 (2-范数) = 1.6025e+13
AA^(-1) 与 I 的 Frobenius 范数误差: 1.5348e-04
结论：AA^(-1) 有明显偏差，逆矩阵存在较大数值误差。

希尔伯特矩阵阶数: n = 12
条件数 (2-范数) = 1.6344e+16
AA^(-1) 与 I 的 Frobenius 范数误差: 2.4233e-01
结论：AA^(-1) 非单位矩阵,逆矩阵已经完全不可靠。

希尔伯特矩阵阶数: n = 14
条件数 (2-范数) = 2.5492e+17
AA^(-1) 与 I 的 Frobenius 范数误差: 4.5187e+00
结论：AA^(-1) 非单位矩阵,逆矩阵已经完全不可靠。



**分析**
- **希尔伯特矩阵**的元素为 $H_{ij} = \dfrac{1}{i+j-1}$，其条件数随阶数 $n$ 急剧增长。
- 对于 $n=14$，条件数已达 $10^{17}$，而双精度浮点数的机器精度 $\varepsilon \approx 2.22\times10^{-16}$，理论误差上界 $\kappa \cdot \varepsilon \approx 10$。这意味着即使右端项无误差，求解 $Ax=b$ 或计算 $A^{-1}$ 也可能产生与真值同量级的误差。
- 计算机存储数字时有舍入误差，矩阵求逆算法（如高斯-约当消元）会将这种误差放大 $\kappa$ 倍。当 $\kappa$ 远大于 $10^{16}$ 时，算法直接失效，甚至在主元选取过程中因消元产生过小的主元而判定矩阵奇异。


- **不要对高阶希尔伯特矩阵（或任何条件数极大的矩阵）直接求逆**。  
- 数值计算中，**$AA^{-1} \neq I$** 是常态，但偏差的量级直接反映了算法的稳定性和矩阵的病态程度。

## 2.4 分块矩阵（Partitioned Matrices）

#### 1. 什么是分块矩阵？
将矩阵用**水平线和垂直线**分割成若干**子矩阵（块）**，称为分块矩阵。

**示例**：
$$A = \begin{bmatrix}
3 & 0 & -1 & 5 & 9 & -2 \\
-5 & 2 & 4 & 0 & -3 & 1 \\
-8 & -6 & 3 & 1 & 7 & -4
\end{bmatrix}
=
\begin{bmatrix}
A_{11} & A_{12} & A_{13} \\
A_{21} & A_{22} & A_{23}
\end{bmatrix}$$

其中：
$$A_{11} = \begin{bmatrix} 3 & 0 & -1 \\ -5 & 2 & 4 \end{bmatrix}, \quad
A_{12} = \begin{bmatrix} 5 & 9 \\ 0 & -3 \end{bmatrix}, \quad
A_{13} = \begin{bmatrix} -2 \\ 1 \end{bmatrix}$$

$$A_{21} = \begin{bmatrix} -8 & -6 & 3 \end{bmatrix}, \quad
A_{22} = \begin{bmatrix} 1 & 7 \end{bmatrix}, \quad
A_{23} = \begin{bmatrix} -4 \end{bmatrix}$$





#### 2. 分块矩阵的加法与数乘
- **加法**：若两个矩阵大小相同且**分块方式完全相同**，则对应块相加：
$$A+B = \begin{bmatrix} A_{11}+B_{11} & A_{12}+B_{12} \\ A_{21}+B_{21} & A_{22}+B_{22} \end{bmatrix}$$

- **数乘**：每个块乘以标量：
$$kA = \begin{bmatrix} kA_{11} & kA_{12} \\ kA_{21} & kA_{22} \end{bmatrix}$$



#### 3. 分块矩阵的乘法
分块矩阵相乘时，把**每个块当作标量**处理，按普通行列规则进行乘法。

> **前提条件（分块相容性）**：左矩阵的**列分块方式**必须与右矩阵的**行分块方式**完全一致。

**示例**：
$$A = \begin{bmatrix}
2 & -3 & 1 & 0 & -4 \\
1 & 5 & -2 & 3 & -1 \\
0 & -4 & -2 & 7 & -1
\end{bmatrix}
= \begin{bmatrix} A_{11} & A_{12} \\ A_{21} & A_{22} \end{bmatrix}, \quad
B = \begin{bmatrix}
6 & 4 \\
-2 & 1 \\
-3 & 7 \\
-1 & 3 \\
5 & 2
\end{bmatrix}
= \begin{bmatrix} B_1 \\ B_2 \end{bmatrix}$$

则：
$$AB = \begin{bmatrix} A_{11} & A_{12} \\ A_{21} & A_{22} \end{bmatrix}
\begin{bmatrix} B_1 \\ B_2 \end{bmatrix}
= \begin{bmatrix} A_{11}B_1 + A_{12}B_2 \\ A_{21}B_1 + A_{22}B_2 \end{bmatrix}$$

> **注意**：每个乘积中子矩阵的顺序不能颠倒（$A$ 的块必须在左边），因为矩阵乘法不满足交换律。




#### 4. 列-行展开（Theorem 10）
若 $A$ 是 $m \times n$，$B$ 是 $n \times p$，则：
$$AB = \sum_{k=1}^{n} \operatorname{col}_k(A) \cdot \operatorname{row}_k(B)$$

其中 $\operatorname{col}_k(A) \operatorname{row}_k(B)$ 是一个**外积**（$m \times 1$ 乘以 $1 \times p$，结果为 $m \times p$ 矩阵）。

**示例验证**：
设 $A = \begin{bmatrix} -3 & 1 & 2 \\ 1 & -4 & 5 \end{bmatrix}$，$B = \begin{bmatrix} a & b \\ c & d \\ e & f \end{bmatrix}$，则：
$$AB = \operatorname{col}_1(A)\operatorname{row}_1(B) + \operatorname{col}_2(A)\operatorname{row}_2(B) + \operatorname{col}_3(A)\operatorname{row}_3(B)$$



#### 5. 分块上三角矩阵的逆（block upper triangular）
设 $A = \begin{bmatrix} A_{11} & A_{12} \\ 0 & A_{22} \end{bmatrix}$ 为分块上三角矩阵，其中 $A_{11}$ 为 $p \times p$，$A_{22}$ 为 $q \times q$，且 $A$ 可逆。

令 $A^{-1} = \begin{bmatrix} B_{11} & B_{12} \\ B_{21} & B_{22} \end{bmatrix}$，由 $A A^{-1} = I$ 得：
$$\begin{bmatrix}
A_{11} & A_{12} \\
0 & A_{22}
\end{bmatrix}
\begin{bmatrix}
B_{11} & B_{12} \\
B_{21} & B_{22}
\end{bmatrix}
=
\begin{bmatrix}
I_p & 0 \\
0 & I_q
\end{bmatrix}$$

展开得到四个方程：
$$A_{11}B_{11} + A_{12}B_{21} = I_p \quad (1)$$
$$A_{11}B_{12} + A_{12}B_{22} = 0 \quad (2)$$
$$A_{22}B_{21} = 0 \quad (3)$$
$$A_{22}B_{22} = I_q \quad (4)$$

求解得到：
$$\boxed{
\begin{bmatrix}
A_{11} & A_{12} \\
0 & A_{22}
\end{bmatrix}^{-1}
=
\begin{bmatrix}
A_{11}^{-1} & -A_{11}^{-1}A_{12}A_{22}^{-1} \\
0 & A_{22}^{-1}
\end{bmatrix}
}$$

### 分块对角矩阵
$$A = \begin{bmatrix} A_{11} & 0 \\ 0 & A_{22} \end{bmatrix}$$

可逆 $\iff$ 每个对角块 $A_{11}$、$A_{22}$ 都可逆，且：
$$A^{-1} = \begin{bmatrix} A_{11}^{-1} & 0 \\ 0 & A_{22}^{-1} \end{bmatrix}$$




#### 6. 分块矩阵的实际用途
1. **超大矩阵计算**：矩阵太大无法一次性装入内存时，分块允许计算机每次只处理两三个子矩阵，大幅降低内存压力。
2. **高性能计算**：某些向量流水线架构的超级计算机在使用分块矩阵算法时计算效率更高。
3. **专业数值计算软件**（如 LAPACK）大量使用分块矩阵计算来优化性能。
4. **实际建模**：分块矩阵自然地反映系统的内部结构（如电路板上的多个芯片、企业各部门间的关联等）。


#### 7. 小结
| 操作 | 规则 |
| :--- | :--- |
| 加法 | 对应块相加（要求分块方式相同） |
| 数乘 | 每个块乘以标量 |
| 乘法 | 如同标量乘法，但需满足分块相容性，且顺序不可颠倒 |
| 列-行展开 | $AB = \sum \operatorname{col}_k(A)\operatorname{row}_k(B)$ |
| 分块上三角求逆 | 主对角线块分别求逆，右上角为 $-A_{11}^{-1}A_{12}A_{22}^{-1}$ |
| 分块对角求逆 | 每个对角块分别求逆 |

### 练习2.4 17
![2-15.png](picture/chapter_2_picture/2-15.png)

将右边三个矩阵相乘：
$$ \begin{bmatrix} I & 0 \\ X & I \end{bmatrix}
\begin{bmatrix} A_{11} & 0 \\ 0 & S \end{bmatrix}
=
\begin{bmatrix} A_{11} & 0 \\ XA_{11} & S \end{bmatrix}$$

再右乘 $\begin{bmatrix} I & Y \\ 0 & I \end{bmatrix}$：
$$ \begin{bmatrix} A_{11} & 0 \\ XA_{11} & S \end{bmatrix}
\begin{bmatrix} I & Y \\ 0 & I \end{bmatrix}
=
\begin{bmatrix} A_{11} & A_{11}Y \\ XA_{11} & XA_{11}Y + S \end{bmatrix}$$

令其等于原矩阵，得到：
$$A_{11}Y = A_{12} \Rightarrow Y = A_{11}^{-1}A_{12}$$
$$XA_{11} = A_{21} \Rightarrow X = A_{21}A_{11}^{-1}$$

最后一个块：
$$XA_{11}Y + S = A_{21}A_{11}^{-1}A_{12} + (A_{22} - A_{21}A_{11}^{-1}A_{12}) = A_{22}$$

因此：
$$\boxed{X = A_{21}A_{11}^{-1}, \quad Y = A_{11}^{-1}A_{12}}$$


### 练习2.4 21
![2-16-1.png](picture/chapter_2_picture/2-16-1.png)
![2-16.png](picture/chapter_2_picture/2-16.png)
![2-17.png](picture/chapter_2_picture/2-17.png)


在工程控制中，通过拉普拉斯变换将微分方程转化为线性方程组：
$$\begin{bmatrix} A - sI_n & B \\ C & I_m \end{bmatrix}
\begin{bmatrix} x \\ u \end{bmatrix}
=
\begin{bmatrix} 0 \\ y \end{bmatrix} \tag{8}$$

其中：
- $A$ 是 $n \times n$，$B$ 是 $n \times m$，$C$ 是 $m \times n$
- $s$ 是复变量
- $u \in \mathbb{R}^m$：系统**输入**
- $y \in \mathbb{R}^m$：系统**输出**
- $x \in \mathbb{R}^n$：系统**状态向量**



**已知**：$A - sI_n$ 可逆。将 (8) 展开为两个矩阵方程：
$$\begin{cases} (A - sI_n)x + B u = 0 & (1) \\ Cx + I_m u = y & (2) \end{cases}$$

**步骤**：

1. **解顶式求 $x$**：
$$(A - sI_n)x = -B u$$
由于 $A - sI_n$ 可逆，两边左乘其逆矩阵：
$$x = -(A - sI_n)^{-1} B u$$

2. **代入底式**：
$$C[-(A - sI_n)^{-1} B u] + u = y$$

3. **整理得标准形式 $W(s)u = y$**：
$$[I_m - C(A - sI_n)^{-1} B]u = y$$

因此，**传递函数**为：
$$\boxed{W(s) = I_m - C(A - sI_n)^{-1} B}$$

 $W(s)$ 与分块系统矩阵的关系

观察(8)左边的系统矩阵：
$$M = \begin{bmatrix} A - sI_n & B \\ C & I_m \end{bmatrix}$$

若将 $M$ 分块，其中左上块 $A_{11} = A - sI_n$，则 $A_{11}$ 的 **Schur complement（舒尔补）** 为：
$$S = A_{22} - A_{21}A_{11}^{-1}A_{12} = I_m - C(A - sI_n)^{-1}B$$

**结论**：
> $W(s)$ 是系统矩阵 $M$ 中左上块 $A - sI_n$ 的 **Schur complement**。  
> （即 $W(s) = I_m - C(A - sI_n)^{-1}B$）



### 练习2.4 22
![2-18.png](picture/chapter_2_picture/2-18.png)


将 $M'$ 分块：
$$A_{11} = A - BC - sI_n, \quad A_{12} = B, \quad A_{21} = -C, \quad A_{22} = I_m$$

Schur complement 的定义（$A_{11}$ 可逆时）为：
$$S = A_{22} - A_{21}A_{11}^{-1}A_{12}$$

代入各块：
$$S = I_m - (-C)(A - BC - sI_n)^{-1}B$$

即：
$$\boxed{S = I_m + C(A - BC - sI_n)^{-1}B}$$

**结合习题 21 的结论**

由习题 21 我们知道，对于原始系统，$W(s) = I_m - C(A - sI_n)^{-1}B$。  
此处对修改后的矩阵求出的舒尔补 $S = I_m + C(A - BC - sI_n)^{-1}B$，**正好等于 $W(s)^{-1}$**（在 $W(s)$ 可逆的前提下）。

因此：
$$\boxed{W(s)^{-1} = I_m + C(A - BC - sI_n)^{-1}B}$$

这符合题目描述：“逆传递函数 $W(s)^{-1}$ 是下列矩阵中 $A - BC - sI_n$ 的 Schur complement。”


- **传递函数 $W(s)$**：系统矩阵 $\begin{bmatrix} A-sI & B \\ C & I \end{bmatrix}$ 中 $A-sI$ 的舒尔补。
- **逆传递函数 $W(s)^{-1}$**：修改后的系统矩阵 $\begin{bmatrix} A-BC-sI & B \\ -C & I \end{bmatrix}$ 中 $A-BC-sI$ 的舒尔补。



### 练习2.4 29
![2-19.png](picture/chapter_2_picture/2-19.png)


**a. 计算 $A + B$**

**方法**

将 $A$ 和 $B$ 按**完全相同的方式**划分为若干块，使得每个块的大小 $\le 32$。例如，将 $50 \times 50$ 矩阵划分为：
- 左上：$25 \times 25$
- 右上：$25 \times 25$
- 左下：$25 \times 25$
- 右下：$25 \times 25$

或划分为：
- 左上：$20 \times 20$
- 右上：$20 \times 30$
- 左下：$30 \times 20$
- 右下：$30 \times 30$

##### 操作步骤
1. 将 $A$ 和 $B$ 按相同方式分块：
   $$A = \begin{bmatrix} A_{11} & A_{12} \\ A_{21} & A_{22} \end{bmatrix}, \quad B = \begin{bmatrix} B_{11} & B_{12} \\ B_{21} & B_{22} \end{bmatrix}$$

2. 逐块相加：
   $$A+B = \begin{bmatrix} A_{11}+B_{11} & A_{12}+B_{12} \\ A_{21}+B_{21} & A_{22}+B_{22} \end{bmatrix}$$

3. 每个子块的和 $(A_{ij}+B_{ij})$ 均在 $32 \times 32$ 限制内完成，最后将结果块组装成 $50 \times 50$ 矩阵。



**b. 计算 $AB$**

**方法**

使用分块矩阵乘法。设 $A$ 的列分块与 $B$ 的行分块**相容**（即 $A$ 的列分组数与 $B$ 的行分组数相同，且对应维度相等）。

##### 操作步骤
1. 将 $A$ 按列划分为两组，$B$ 按行划分为对应的两组。例如：
   $$A = \begin{bmatrix} A_{11} & A_{12} \\ A_{21} & A_{22} \end{bmatrix}, \quad B = \begin{bmatrix} B_{11} & B_{12} \\ B_{21} & B_{22} \end{bmatrix}$$
   其中 $A_{11}$ 为 $25 \times 25$，$A_{12}$ 为 $25 \times 25$，$B_{11}$ 为 $25 \times 25$，$B_{21}$ 为 $25 \times 25$ 等。

2. 按分块乘法规则计算 $C = AB$ 的每个块：
   $$C_{11} = A_{11}B_{11} + A_{12}B_{21}$$
   $$C_{12} = A_{11}B_{12} + A_{12}B_{22}$$
   $$C_{21} = A_{21}B_{11} + A_{22}B_{21}$$
   $$C_{22} = A_{21}B_{12} + A_{22}B_{22}$$

3. 每个子块乘积（如 $A_{11}B_{11}$）均在 $32 \times 32$ 限制内完成，每次加法也只涉及两个 $32 \times 32$ 以下的矩阵。


**c. 求解 $Ax = b$**

$A$ 可划分为 $2 \times 2$ 分块矩阵：
$$A = \begin{bmatrix} A_{11} & 0 \\ A_{21} & A_{22} \end{bmatrix}$$
其中：
- $A_{11}$ 是 $20 \times 20$ 可逆矩阵
- $A_{22}$ 是 $30 \times 30$ 可逆矩阵
- $A_{12} = 0$（零矩阵）

将 $x$ 和 $b$ 按同样方式分块：
$$x = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}, \quad b = \begin{bmatrix} b_1 \\ b_2 \end{bmatrix}$$
其中 $x_1, b_1 \in \mathbb{R}^{20}$，$x_2, b_2 \in \mathbb{R}^{30}$。

**求解步骤**

方程 $Ax = b$ 展开为：
$$\begin{cases} A_{11}x_1 = b_1 & (1) \\ A_{21}x_1 + A_{22}x_2 = b_2 & (2) \end{cases}$$

**1**：解小系统 (1)
- 使用矩阵程序求解 $20$ 阶方程 $A_{11}x_1 = b_1$
- 得到 $x_1$

**2**：计算中间量
- 计算 $A_{21}x_1$

**3**：解小系统 (2)
- 将 $A_{21}x_1$ 移到右端：
  $$A_{22}x_2 = b_2 - A_{21}x_1$$
- 使用矩阵程序求解 $30$ 阶方程，得到 $x_2$

**4**：组装解
- 将 $x_1$ 和 $x_2$ 拼成完整的 $50$ 维向量 $x$



## 2.5 矩阵分解（Matrix Factorizations）

#### 1. 矩阵分解的概念
- **矩阵分解**：将矩阵 $A$ 表示为两个或多个矩阵的乘积 $A = LU$。
- **目的**：对数据进行“预处理”，将 $A$ 分解为若干结构更简单的部分，便于计算和理论分析。
- 与矩阵乘法的“合成数据”相反，分解是“分析数据”。

#### 2. LU 分解的动机

##### 应用场景
求解一系列具有**相同系数矩阵**的线性方程组：
$$A\mathbf{x} = \mathbf{b}_1, \quad A\mathbf{x} = \mathbf{b}_2, \quad \ldots, \quad A\mathbf{x} = \mathbf{b}_p$$

##### 为什么不用求逆？
- 直接计算 $A^{-1}$ 再乘以 $\mathbf{b}$ 运算量大（约 $2n^3$ 次浮点运算）。
- 先用行化简得到 $A$ 的 LU 分解，后续每个方程只需 **$2n^2$ 次运算**，且数值稳定性更好。


#### 3. LU 分解的定义（无行交换情况）

若 $A$ 可通过 **行替换操作**（只将某一行的倍数加到另一行下方）化为行阶梯形 $U$，则：
$$A = L U$$
其中：
- $L$：$m \times m$ **单位下三角矩阵**（对角线全为 1）
- $U$：$m \times n$ **行阶梯形矩阵**（即 $A$ 的 echelon form）

##### 图解（示意图）
$$A = \begin{bmatrix}
* & * & * & * \\
* & * & * & * \\
* & * & * & * \\
* & * & * & *
\end{bmatrix}
= 
\begin{bmatrix}
1 & 0 & 0 & 0 \\
* & 1 & 0 & 0 \\
* & * & 1 & 0 \\
* & * & * & 1
\end{bmatrix}
\begin{bmatrix}
* & * & * & * \\
0 & * & * & * \\
0 & 0 & * & * \\
0 & 0 & 0 & *
\end{bmatrix}$$



#### 4. 为什么 LU 分解有用？

若 $A = LU$，方程 $A\mathbf{x} = \mathbf{b}$ 可写为：
$$L(U\mathbf{x}) = \mathbf{b}$$

令 $\mathbf{y} = U\mathbf{x}$，则分两步求解：

1. **前代（Forward substitution）**：解 $L\mathbf{y} = \mathbf{b}$  
   （因为 $L$ 是下三角，直接从上往下代入）
   
2. **回代（Back substitution）**：解 $U\mathbf{x} = \mathbf{y}$  
   （因为 $U$ 是上三角，从下往上回代）





#### 5. LU 分解算法

**思想**：对 $A$ 进行行替换操作（将某行倍数加到下方行）化为 $U$，同时记录操作信息到 $L$。

##### 步骤
1. 将 $A$ 化为行阶梯形 $U$（只使用向下行替换）。
2. 将各列中用于消元的“乘数”（即行替换时的倍数）填入 $L$ 的对应位置：
   - 每次将第 $j$ 行乘以某数加到第 $i$ 行时，$l_{ij}$ 就是这个“某数”（注意符号：若操作是“把 $-4$ 倍行1加到行3”，则 $l_{31} = 4$，因为在 $L$ 中填入的是**加回去的倍数**）。

##### 教材 Example 2 摘要
设 $A$ 通过行操作化为 $U$，则 $L$ 的第一列由 $A$ 第一列除以主元得到，后续列同理。最终验证 $LU = A$。

> **关键公式**：若 $E_p \cdots E_1 A = U$，则 $L = (E_p \cdots E_1)^{-1}$，且 $A = LU$。



##### 6. 实际考虑：行交换与部分主元

- 为**数值精度**，实际计算常用**部分主元**（partial pivoting）：在每列选绝对值最大的元素作为 pivot，必要时交换行。
- 行交换会破坏 $L$ 的“纯下三角”性质，但可得到 **带置换的 LU 分解**（$PA = LU$，其中 $P$ 是置换矩阵）。
- 现代软件中的“LU 分解”通常默认允许行交换，$L$ 可能是一个“置换下三角”矩阵。



##### 7. 运算量对比（$n \times n$ 稠密矩阵）

| 操作 | 浮点运算量 |
| :--- | :--- |
| LU 分解（计算 $L,U$） | $\approx \frac{2}{3}n^3$ |
| 求 $A^{-1}$ | $\approx 2n^3$ |
| 用 $L,U$ 解一个方程（前代+回代） | $\approx 2n^2$ |
| 用 $A^{-1}\mathbf{b}$ 解一个方程 | $\approx 2n^2$（但需先求 $A^{-1}$，且误差更大） |

> **稀疏矩阵**（大多零元素）时，$L,U$ 可能仍是稀疏的，而 $A^{-1}$ 通常稠密，此时 LU 分解优势更加明显。


##### 8. 电气工程中的应用：电路网络的转移矩阵

##### 背景
- 电路网络（如梯形网络）的输入输出关系由**转移矩阵** $A$ 描述：
  $$\begin{bmatrix} v_2 \\ i_2 \end{bmatrix} = A \begin{bmatrix} v_1 \\ i_1 \end{bmatrix}$$
- 两个电路串联时，总转移矩阵 = 各分电路转移矩阵的**乘积**（注意顺序）。

##### 梯形网络示例
- **串联电路**（电阻 $R_1$）：$A_1 = \begin{bmatrix} 1 & -R_1 \\ 0 & 1 \end{bmatrix}$
- **并联电路**（电阻 $R_2$）：$A_2 = \begin{bmatrix} 1 & 0 \\ -1/R_2 & 1 \end{bmatrix}$

串联后的总转移矩阵：
$$A = A_2 A_1 = \begin{bmatrix} 1 & -R_1 \\ -1/R_2 & 1 + R_1/R_2 \end{bmatrix}$$

**设计问题**：给定目标矩阵 $\begin{bmatrix} 1 & -8 \\ -5 & 5 \end{bmatrix}$，可通过匹配元素找到 $R_1=8$，$R_2=2$，从而用两个简单电路实现该网络。

> 这本质上就是**矩阵分解**的工程应用：将复杂转移矩阵分解为已知基本电路的组合。




##### 9. 总结
- **LU 分解** $A = LU$ 是将 $A$ 分解为下三角 $L$ 和上三角 $U$。
- 用于高效求解**同系数矩阵**的多个线性方程组。
- 构造 $L$ 时记录行替换的倍数，无需额外计算。
- 实际计算中结合行交换（部分主元）保证数值稳定。
- 运算量远小于求逆，且对稀疏矩阵优势明显。
- 矩阵分解思想在电路设计、控制理论等领域有直接应用。


### 练习2.5 11、15 LU分解
![2-20.png](picture/chapter_2_picture/2-20.png)
![2-21.png](picture/chapter_2_picture/2-21.png)

11：

**第 1 列消元**：
- 主元 $a_{11} = 3$
- $l_{21} = 6/3 = 2$，操作：第2行减去 $2\times$ 第1行
- $l_{31} = -1/3$，操作：第3行减去 $(-1/3)\times$ 第1行（即加上 $1/3$ 倍第1行）

消元后：
$$A^{(1)} = \begin{bmatrix}
3 & -6 & 3 \\
0 & 5 & -4 \\
0 & 5 & 1
\end{bmatrix}$$

**第 2 列消元**：
- 主元 $a_{22} = 5$
- $l_{32} = 5/5 = 1$，操作：第3行减去 $1\times$ 第2行

消元后：
$$U = \begin{bmatrix}
3 & -6 & 3 \\
0 & 5 & -4 \\
0 & 0 & 5
\end{bmatrix}$$

**下三角矩阵 $L$**：
$$L = \begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
-\frac{1}{3} & 1 & 1
\end{bmatrix}$$

**验证 $A = LU$**

$$LU = \begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
-\frac{1}{3} & 1 & 1
\end{bmatrix}
\begin{bmatrix}
3 & -6 & 3 \\
0 & 5 & -4 \\
0 & 0 & 5
\end{bmatrix}
= \begin{bmatrix}
3 & -6 & 3 \\
6 & -7 & 2 \\
-1 & 7 & 0
\end{bmatrix} = A$$





15：

**第 1 列消元**：
- 主元 $a_{11} = 2$
- $l_{21} = 6/2 = 3$，操作：第2行减去 $3\times$ 第1行
- $l_{31} = -1/2$，操作：第3行减去 $(-1/2)\times$ 第1行（即加上 $1/2$ 倍第1行）

消元后：
$$A^{(1)} = \begin{bmatrix}
2 & -4 & 4 & -2 \\
0 & 3 & -5 & 3 \\
0 & -6 & 10 & -1
\end{bmatrix}$$

**第 2 列消元**：
- 主元 $a_{22} = 3$
- $l_{32} = -6/3 = -2$，操作：第3行减去 $(-2)\times$ 第2行（即加上 $2$ 倍第2行）

消元后：
$$U = \begin{bmatrix}
2 & -4 & 4 & -2 \\
0 & 3 & -5 & 3 \\
0 & 0 & 0 & 5
\end{bmatrix}$$

**下三角矩阵 $L$**：
$$L = \begin{bmatrix}
1 & 0 & 0 \\
3 & 1 & 0 \\
-\frac{1}{2} & -2 & 1
\end{bmatrix}$$

**验证 $A = LU$**
$$LU = \begin{bmatrix}
1 & 0 & 0 \\
3 & 1 & 0 \\
-\frac{1}{2} & -2 & 1
\end{bmatrix}
\begin{bmatrix}
2 & -4 & 4 & -2 \\
0 & 3 & -5 & 3 \\
0 & 0 & 0 & 5
\end{bmatrix}
= \begin{bmatrix}
2 & -4 & 4 & -2 \\
6 & -9 & 7 & -3 \\
-1 & -4 & 8 & 0
\end{bmatrix} = A$$


### 练习2.5 22
![2-22.png](picture/chapter_2_picture/2-22.png)


首先对 $A$ 进行 **LU 分解**，得到 $A = L U$，其中 $L$ 是 $5 \times 5$ 单位下三角矩阵，$U$ 是 $5 \times 4$ 行阶梯形矩阵。

通过高斯消元，得到：
$$L = \begin{bmatrix}
1 & 0 & 0 & 0 & 0 \\
3 & 1 & 0 & 0 & 0 \\
1 & -1 & 1 & 0 & 0 \\
2 & 2 & -1 & 1 & 0 \\
-3 & -3 & 2 & 0 & 1
\end{bmatrix}, \qquad
U = \begin{bmatrix}
2 & -4 & -2 & 3 \\
0 & 3 & 1 & -1 \\
0 & 0 & 0 & 5 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{bmatrix}$$

由于 $U$ 只有前 $3$ 行非零，令：
- $B$ = $L$ 的前 $3$ 列（$5 \times 3$）
- $C$ = $U$ 的前 $3$ 行（$3 \times 4$）

即：
$$B = \begin{bmatrix}
1 & 0 & 0 \\
3 & 1 & 0 \\
1 & -1 & 1 \\
2 & 2 & -1 \\
-3 & -3 & 2
\end{bmatrix}, \qquad
C = \begin{bmatrix}
2 & -4 & -2 & 3 \\
0 & 3 & 1 & -1 \\
0 & 0 & 0 & 5
\end{bmatrix}$$

验证：
$$BC = \begin{bmatrix}
1 & 0 & 0 \\
3 & 1 & 0 \\
1 & -1 & 1 \\
2 & 2 & -1 \\
-3 & -3 & 2
\end{bmatrix}
\begin{bmatrix}
2 & -4 & -2 & 3 \\
0 & 3 & 1 & -1 \\
0 & 0 & 0 & 5
\end{bmatrix}
= \begin{bmatrix}
2 & -4 & -2 & 3 \\
6 & -9 & -5 & 8 \\
2 & -7 & -3 & 9 \\
4 & -2 & -2 & -1 \\
-6 & 3 & 3 & 4
\end{bmatrix} = A.$$


**推广（Generalization）**
若 $A$ 是 $m \times n$ 矩阵，且其 LU 分解为 $A = LU$，其中 $U$ 有 $r$ 个非零行（即 $\operatorname{rank}(A)=r$），则：
- 取 $B$ 为 $L$ 的前 $r$ 列（$m \times r$）
- 取 $C$ 为 $U$ 的前 $r$ 行（$r \times n$）

则 $A = BC$，这称为 **Reduced LU Factorization** 或 **秩分解**。



### 练习2.5 23
![2-23.png](picture/chapter_2_picture/2-23.png)

**a.** 若 $A = CD$，$C$ 为 $m \times 4$，$D$ 为 $4 \times n$，则 $A$ 可写作四个外积之和：$A = \mathbf{c}_1 \mathbf{d}_1^T + \mathbf{c}_2 \mathbf{d}_2^T + \mathbf{c}_3 \mathbf{d}_3^T + \mathbf{c}_4 \mathbf{d}_4^T$，其中 $\mathbf{c}_i$ 为 $C$ 的第 $i$ 列，$\mathbf{d}_i^T$ 为 $D$ 的第 $i$ 行。

**b.** 当 $m=400, n=100$ 时，存储 $A$ 需要 $400 \times 100 = 40000$ 个数值；而存储 $C$ (400×4) 和 $D$ (4×100) 仅需 $400\times4 + 4\times100 = 1600 + 400 = 2000$ 个数值，节省大量内存。



### 练习2.5 24
![2-24.png](picture/chapter_2_picture/2-24.png)


设 $A = QR$，$R$ 可逆上三角，$Q^TQ = I$。  
对于 $A\mathbf{x} = \mathbf{b}$，有 $QR\mathbf{x} = \mathbf{b}$，左乘 $Q^T$ 得 $R\mathbf{x} = Q^T\mathbf{b}$。  
由于 $R$ 可逆，可回代求解：$\mathbf{x} = R^{-1}Q^T\mathbf{b}$。  
计算时先求 $\mathbf{y} = Q^T\mathbf{b}$，再解上三角系统 $R\mathbf{x} = \mathbf{y}$。



### 练习2.5 25
![2-25.png](picture/chapter_2_picture/2-25.png)

设 $A = U D V^T$，$U^TU = I$，$V^TV = I$，$D$ 对角元 $\sigma_i > 0$。  
则 $A$ 可逆，且 $A^{-1} = V D^{-1} U^T$，因为：
$$A \cdot V D^{-1} U^T = U D V^T V D^{-1} U^T = U D D^{-1} U^T = U U^T = I.$$




### 练习2.5 26
![2-26.png](picture/chapter_2_picture/2-26.png)

若 $A = P D P^{-1}$，$D = \begin{bmatrix} \lambda_1 & 0 & 0 \\ 0 & \lambda_2 & 0 \\ 0 & 0 & \lambda_3 \end{bmatrix}$，则
$$A^k = P D^k P^{-1} = P \begin{bmatrix} \lambda_1^k & 0 & 0 \\ 0 & \lambda_2^k & 0 \\ 0 & 0 & \lambda_3^k \end{bmatrix} P^{-1}.$$
计算高次幂时只需将每个特征值取 $k$ 次方，大大简化。




### 练习2.5 27
![2-27.png](picture/chapter_2_picture/2-27.png)

一个梯形网络由**串联电阻** $R_1$ 和**并联电阻** $R_2$ 组成，其转移矩阵为：
$$A = \begin{bmatrix}
1 & -R_1 \\
-\frac{1}{R_2} & 1 + \frac{R_1}{R_2}
\end{bmatrix}$$

输入向量 $\mathbf{u} = \begin{bmatrix} 12 \\ 6 \end{bmatrix}$，输出向量 $\mathbf{y} = \begin{bmatrix} 9 \\ 4 \end{bmatrix}$，满足：
$$\begin{bmatrix} 9 \\ 4 \end{bmatrix} = A \begin{bmatrix} 12 \\ 6 \end{bmatrix}$$


$$9 = 12 - 6R_1 \quad \Rightarrow \quad 6R_1 = 3 \quad \Rightarrow \quad R_1 = 0.5\ \Omega$$

$$4 = -\frac{12}{R_2} + 6\left(1 + \frac{R_1}{R_2}\right)$$
代入 $R_1 = 0.5$：
$$4 = -\frac{12}{R_2} + 6 + \frac{3}{R_2} = 6 - \frac{9}{R_2}$$
$$\frac{9}{R_2} = 2 \quad \Rightarrow \quad R_2 = 4.5\ \Omega$$

- **串联电阻**：$R_1 = 0.5\ \Omega$
- **并联电阻**：$R_2 = 4.5\ \Omega$

电路拓扑：输入 → 串联电阻 $0.5\Omega$ → 并联电阻 $4.5\Omega$ → 输出。


将串联和并联的顺序互换：
- 输入 → 并联电阻 $R_2'$ → 串联电阻 $R_1'$ → 输出。

其转移矩阵为：
$$A' = \begin{bmatrix}
1 & 0 \\
-\frac{1}{R_2'} & 1
\end{bmatrix}
\begin{bmatrix}
1 & -R_1' \\
0 & 1
\end{bmatrix}
= \begin{bmatrix}
1 & -R_1' \\
-\frac{1}{R_2'} & 1 + \frac{R_1'}{R_2'}
\end{bmatrix}$$

这形式与标准梯形相同，所以只需取 $R_1' = 0.5\ \Omega$，$R_2' = 4.5\ \Omega$，但是拓扑顺序相反（先并联后串联）。




### 练习2.5 28
![2-28.png](picture/chapter_2_picture/2-28.png)

并联电路转移矩阵为 $A_i = \begin{bmatrix} 1 & 0 \\ -1/R_i & 1 \end{bmatrix}$。  
串联三个的转移矩阵为 $A_3 A_2 A_1$（按顺序）。计算得：
$$A_3 A_2 A_1 = \begin{bmatrix} 1 & 0 \\ -1/R_3 & 1 \end{bmatrix} \begin{bmatrix} 1 & 0 \\ -1/R_2 & 1 \end{bmatrix} \begin{bmatrix} 1 & 0 \\ -1/R_1 & 1 \end{bmatrix} = \begin{bmatrix} 1 & 0 \\ -(1/R_1+1/R_2+1/R_3) & 1 \end{bmatrix}.$$
这正好是一个并联电路的转移矩阵，其等效电阻 $R$ 满足 $1/R = 1/R_1+1/R_2+1/R_3$，即 $R = (1/R_1+1/R_2+1/R_3)^{-1}$。

### 练习2.5 29
![2-29.png](picture/chapter_2_picture/2-29.png)


a. 计算传递矩阵

电路中两个基本模块的传递矩阵：

**并联电阻（Shunt）**：
$$S(R) = \begin{bmatrix} 1 & 0 \\ -\frac{1}{R} & 1 \end{bmatrix}$$

**串联电阻（Series）**：
$$T(R) = \begin{bmatrix} 1 & -R \\ 0 & 1 \end{bmatrix}$$


因此整体传递矩阵为：
$$A = S(R_3) \cdot T(R_2) \cdot S(R_1)$$


计算 $T(R_2) \cdot S(R_1)$
$$T(R_2) \cdot S(R_1) =
\begin{bmatrix} 1 & -R_2 \\ 0 & 1 \end{bmatrix}
\begin{bmatrix} 1 & 0 \\ -\frac{1}{R_1} & 1 \end{bmatrix}
=
\begin{bmatrix}
1 + \frac{R_2}{R_1} & -R_2 \\
-\frac{1}{R_1} & 1
\end{bmatrix}$$

左乘 $S(R_3)$
$$A =
\begin{bmatrix} 1 & 0 \\ -\frac{1}{R_3} & 1 \end{bmatrix}
\begin{bmatrix}
1 + \frac{R_2}{R_1} & -R_2 \\
-\frac{1}{R_1} & 1
\end{bmatrix}$$

**最终结果**：
$$\boxed{
A =
\begin{bmatrix}
1 + \frac{R_2}{R_1} & -R_2 \\
-\left( \frac{1}{R_1} + \frac{1}{R_3} + \frac{R_2}{R_1 R_3} \right) & 1 + \frac{R_2}{R_3}
\end{bmatrix}
}$$



b. 设计梯形网络

目标矩阵：
$$A = \begin{bmatrix} \frac{4}{3} & -12 \\ -\frac{1}{4} & 3 \end{bmatrix}$$
可分解为a中的形式。

**由 $(1,2)$ 位置**：
$$-R_2 = -12 \quad \Rightarrow \quad \boxed{R_2 = 12\ \Omega}$$

**由 $(1,1)$ 位置**：
$$1 + \frac{R_2}{R_1} = \frac{4}{3}$$
代入 $R_2 = 12$：
$$\frac{12}{R_1} = \frac{1}{3} \quad \Rightarrow \quad \boxed{R_1 = 36\ \Omega}$$

**由 $(2,2)$ 位置**：
$$1 + \frac{R_2}{R_3} = 3$$
代入 $R_2 = 12$：
$$\frac{12}{R_3} = 2 \quad \Rightarrow \quad \boxed{R_3 = 6\ \Omega}$$

验证 $(2,1)$ 位置

代入 $R_1=36, R_2=12, R_3=6$：
$$-\left( \frac{1}{36} + \frac{1}{6} + \frac{12}{36 \times 6} \right)
= -\left( \frac{1}{36} + \frac{6}{36} + \frac{2}{36} \right)
= -\frac{9}{36}
= -\frac{1}{4}$$

**结论**
设计的梯形网络：
$$\boxed{\text{并联电阻 } 36\ \Omega \longrightarrow \text{串联电阻 } 12\ \Omega \longrightarrow \text{并联电阻 } 6\ \Omega}$$

### 练习2.5 30
![2-30.png](picture/chapter_2_picture/2-30.png)

选择拓扑顺序为（输入 → 输出）：
$$\text{串联电阻 } R_1 \longrightarrow \text{并联电阻 } R_2 \longrightarrow \text{串联电阻 } R_3$$

对应的传递矩阵为：
$$A = T(R_3) \cdot S(R_2) \cdot T(R_1)$$



将矩阵形式展开：
$$T(R_3) \cdot S(R_2) \cdot T(R_1) =
\begin{bmatrix} 1 & -R_3 \\ 0 & 1 \end{bmatrix}
\begin{bmatrix} 1 & 0 \\ -\frac{1}{R_2} & 1 \end{bmatrix}
\begin{bmatrix} 1 & -R_1 \\ 0 & 1 \end{bmatrix}$$

先计算 $S(R_2) \cdot T(R_1)$：
$$S(R_2) \cdot T(R_1) =
\begin{bmatrix} 1 & -R_1 \\ -\frac{1}{R_2} & 1 + \frac{R_1}{R_2} \end{bmatrix}$$

再左乘 $T(R_3)$：
$$A =
\begin{bmatrix} 1 & -R_3 \\ 0 & 1 \end{bmatrix}
\begin{bmatrix} 1 & -R_1 \\ -\frac{1}{R_2} & 1 + \frac{R_1}{R_2} \end{bmatrix}$$

计算得到：
$$A =
\begin{bmatrix}
1 + \frac{R_3}{R_2} & -R_1 - R_3\left(1 + \frac{R_1}{R_2}\right) \\
-\frac{1}{R_2} & 1 + \frac{R_1}{R_2}
\end{bmatrix}
= \begin{bmatrix}
\frac{4}{3} & -12 \\
-\frac{1}{4} & 3
\end{bmatrix}$$



**由 $(2,1)$ 位置**：
$$-\frac{1}{R_2} = -\frac{1}{4} \quad \Rightarrow \quad \boxed{R_2 = 4\ \Omega}$$

**由 $(2,2)$ 位置**：
$$1 + \frac{R_1}{R_2} = 3 \quad \Rightarrow \quad \frac{R_1}{4} = 2 \quad \Rightarrow \quad \boxed{R_1 = 8\ \Omega}$$

**由 $(1,1)$ 位置**：
$$1 + \frac{R_3}{R_2} = \frac{4}{3} \quad \Rightarrow \quad \frac{R_3}{4} = \frac{1}{3} \quad \Rightarrow \quad \boxed{R_3 = \frac{4}{3}\ \Omega}$$

**验证 $(1,2)$ 位置**：
代入 $R_1=8, R_2=4, R_3=\frac{4}{3}$：
$$-R_1 - R_3\left(1 + \frac{R_1}{R_2}\right) = -8 - \frac{4}{3}\left(1 + \frac{8}{4}\right) = -8 - \frac{4}{3}(1+2) = -8 - 4 = -12$$


$$\boxed{
A =
\begin{bmatrix} 1 & -\frac{4}{3} \\ 0 & 1 \end{bmatrix}
\cdot
\begin{bmatrix} 1 & 0 \\ -\frac{1}{4} & 1 \end{bmatrix}
\cdot
\begin{bmatrix} 1 & -8 \\ 0 & 1 \end{bmatrix}
}$$


$$\text{输入} \longrightarrow \boxed{\text{串联 } 8\Omega} \longrightarrow \boxed{\text{并联 } 4\Omega} \longrightarrow \boxed{\text{串联 } \frac{4}{3}\Omega} \longrightarrow \text{输出}$$


### 练习2.5 31
![2-31.png](picture/chapter_2_picture/2-31.png)
![2-32.png](picture/chapter_2_picture/2-32.png)

In [61]:
# 构造矩阵 A
A = np.array([
    [4, -1, -1, 0, 0, 0, 0, 0],
    [-1, 4, 0, -1, 0, 0, 0, 0],
    [-1, 0, 4, -1, -1, 0, 0, 0],
    [0, -1, -1, 4, 0, -1, 0, 0],
    [0, 0, -1, 0, 4, -1, -1, 0],
    [0, 0, 0, -1, -1, 4, 0, -1],
    [0, 0, 0, 0, -1, 0, 4, -1],
    [0, 0, 0, 0, 0, -1, -1, 4]
], dtype=float)

b = np.array([5, 15, 0, 10, 0, 10, 20, 30], dtype=float)

# LU 分解
n = A.shape[0]
L = np.eye(n)          # 单位下三角
U = A.copy()           # 上三角

for k in range(n-1):
    for i in range(k+1, n):
        L[i, k] = U[i, k] / U[k, k]
        # 行替换操作：第 i 行减去 L[i,k] 倍的第 k 行
        for j in range(k, n):
            U[i, j] -= L[i, k] * U[k, j]

# 检查 LU - A
LU_minus_A = L @ U - A
print("a. LU - A 的 Frobenius 范数：", np.linalg.norm(LU_minus_A))
print("   LU - A 的最大绝对值元素：", np.max(np.abs(LU_minus_A)))

# ---------- 求解 Ly = b ----------
y = np.zeros(n)
for i in range(n):
    y[i] = b[i] - np.dot(L[i, :i], y[:i])   # L[i,i]=1

# ---------- 求解 Ux = y ----------
x = np.zeros(n)
for i in range(n-1, -1, -1):
    x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]

print("\nb. 求解得到的 x =", x)

# 用 numpy 内置求解验证
x_true = np.linalg.solve(A, b)
print("\n内置求解 x =", x_true)
print("两者误差范数：", np.linalg.norm(x - x_true))

# 计算逆矩阵
A_inv = np.linalg.inv(A)

print("A^{-1} =")
print(A_inv)

print("\nA^{-1} 的非零元素个数：", np.count_nonzero(np.abs(A_inv) > 1e-15))
print("A^{-1} 的总元素个数：", A_inv.size)
print("A^{-1} 的密度：", np.count_nonzero(np.abs(A_inv) > 1e-15) / A_inv.size)


a. LU - A 的 Frobenius 范数： 1.9348667151521432e-16
   LU - A 的最大绝对值元素： 1.1102230246251565e-16

b. 求解得到的 x = [ 3.9569378   6.58851675  4.23923445  7.39712919  5.60287081  8.76076555
  9.41148325 12.0430622 ]

内置求解 x = [ 3.9569378   6.58851675  4.23923445  7.39712919  5.60287081  8.76076555
  9.41148325 12.0430622 ]
两者误差范数： 2.6645352591003757e-15
A^{-1} =
[[0.29526481 0.08655337 0.09450586 0.05094869 0.03180993 0.02273552
  0.00999835 0.00818347]
 [0.08655337 0.29526481 0.05094869 0.09450586 0.02273552 0.03180993
  0.00818347 0.00999835]
 [0.09450586 0.05094869 0.32707474 0.1092889  0.10450421 0.05913216
  0.03180993 0.02273552]
 [0.05094869 0.09450586 0.1092889  0.32707474 0.05913216 0.10450421
  0.02273552 0.03180993]
 [0.03180993 0.02273552 0.10450421 0.05913216 0.32707474 0.1092889
  0.09450586 0.05094869]
 [0.02273552 0.03180993 0.05913216 0.10450421 0.1092889  0.32707474
  0.05094869 0.09450586]
 [0.00999835 0.00818347 0.03180993 0.02273552 0.09450586 0.05094869
  0.29526481 0.086553

### 练习2.5 32
![2-33.png](picture/chapter_2_picture/2-33.png)

In [55]:
#LU 分解
def lu_tridiagonal(A):
    """
    对三对角矩阵 A 进行 LU 分解，返回 L 和 U（均为双对角）。
    """
    n = A.shape[0]
    L = np.eye(n)
    U = A.copy()
    
    for k in range(n-1):
        # 主元
        pivot = U[k, k]
        # 计算乘数
        l_ik = U[k+1, k] / pivot
        L[k+1, k] = l_ik
        # 行替换：第 k+1 行减去 l_ik 倍的第 k 行
        U[k+1, k] = 0.0
        U[k+1, k+1] -= l_ik * U[k, k+1]
    
    return L, U

# 构造矩阵 A (C=1)
n = 5
A = np.zeros((n, n))
for i in range(n):
    A[i, i] = 3
for i in range(n-1):
    A[i, i+1] = -1
    A[i+1, i] = -1

L, U = lu_tridiagonal(A)

print("a. LU 分解结果：")
print("L = \n", L)
print("U = \n", U)
print("验证 LU - A 的 Frobenius 范数：", np.linalg.norm(L @ U - A))

#利用 LU 分解求解递推
def solve_with_LU(L, U, b):
    """求解 LU x = b，返回 x"""
    n = len(b)
    # 前代 Ly = b
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    # 回代 Ux = y
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    return x

t0 = np.array([10, 12, 12, 12, 10], dtype=float)
t = t0.copy()
print("\nb. 温度分布：")
print(f"t0 = {t0}")

for k in range(1, 5):
    t = solve_with_LU(L, U, t)   # 解 A t_new = t_old
    print(f"t{k} = {t}")

a. LU 分解结果：
L = 
 [[ 1.          0.          0.          0.          0.        ]
 [-0.33333333  1.          0.          0.          0.        ]
 [ 0.         -0.375       1.          0.          0.        ]
 [ 0.          0.         -0.38095238  1.          0.        ]
 [ 0.          0.          0.         -0.38181818  1.        ]]
U = 
 [[ 3.         -1.          0.          0.          0.        ]
 [ 0.          2.66666667 -1.          0.          0.        ]
 [ 0.          0.          2.625      -1.          0.        ]
 [ 0.          0.          0.          2.61904762 -1.        ]
 [ 0.          0.          0.          0.          2.61818182]]
验证 LU - A 的 Frobenius 范数： 0.0

b. 温度分布：
t0 = [10. 12. 12. 12. 10.]
t1 = [ 6.55555556  9.66666667 10.44444444  9.66666667  6.55555556]
t2 = [4.74074074 7.66666667 8.59259259 7.66666667 4.74074074]
t3 = [3.59876543 6.05555556 6.90123457 6.05555556 3.59876543]
t4 = [2.79218107 4.77777778 5.48559671 4.77777778 2.79218107]


## 2.6 列昂惕夫投入产出模型（Leontief Input-Output Model）

#### 核心方程
列昂惕夫投入产出模型描述经济中各部门生产与需求的关系：
$$\mathbf{x} = C\mathbf{x} + \mathbf{d}$$

- $\mathbf{x}$：**生产向量**（各部门总产出）
- $C$：**消耗矩阵**（$C_{ij}$ 表示部门 $j$ 生产 1 单位产品需要消耗部门 $i$ 的投入量）
- $\mathbf{d}$：**最终需求向量**（非生产部门的需求）

等价形式：
$$(I - C)\mathbf{x} = \mathbf{d}$$

#### 定理 11（存在性与非负性）
若 $C$ 和 $\mathbf{d}$ 的所有元素非负，且 $C$ 的**每一列的列和都小于 1**，则：
1. $(I - C)$ 可逆
2. 生产向量 $\mathbf{x} = (I - C)^{-1}\mathbf{d}$ 有非负元素
3. 这是方程 $\mathbf{x} = C\mathbf{x} + \mathbf{d}$ 的唯一解

#### $(I - C)^{-1}$ 的级数展开
如果 $C$ 的列和都小于 1，则 $C^m \to 0$（$m \to \infty$），并且：
$$(I - C)^{-1} = I + C + C^2 + C^3 + \cdots$$

#### 经济意义
- $(I - C)^{-1}$ 的第 $j$ 列表示：**若最终需求增加 1 单位（部门 $j$），各部门需要额外生产的数量**。
- 这种级数展开也提供了数值计算 $(I - C)^{-1}$ 的一种方法（迭代逼近）。


## 2.7 计算机图形学（Applications to Computer Graphics）

#### 齐次坐标（Homogeneous Coordinates）
为了用矩阵乘法统一表示平移、旋转、缩放等变换，引入齐次坐标：
- 2D 点 $(x, y)$ 表示为 $(x, y, 1)$
- 3D 点 $(x, y, z)$ 表示为 $(x, y, z, 1)$

一般地，$(X, Y, Z, H)$ 对应点 $(X/H, Y/H, Z/H)$（$H \neq 0$）。

#### 基本 2D 变换矩阵（齐次坐标下）

| 变换类型 | 矩阵形式 |
| :--- | :--- |
| **平移(Translate)**（$h, k$） | $\begin{bmatrix} 1 & 0 & h \\ 0 & 1 & k \\ 0 & 0 & 1 \end{bmatrix}$ |
| **缩放(Scale)**（$s_x, s_y$） | $\begin{bmatrix} s_x & 0 & 0 \\ 0 & s_y & 0 \\ 0 & 0 & 1 \end{bmatrix}$ |
| **旋转(Rotate)**（角度 $\theta$） | $\begin{bmatrix} \cos\theta & -\sin\theta & 0 \\ \sin\theta & \cos\theta & 0 \\ 0 & 0 & 1 \end{bmatrix}$ |
| **剪切**（$k$） | $\begin{bmatrix} 1 & k & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$ |

#### 复合变换
多个变换的组合对应矩阵乘法（**注意顺序：后执行的变换在左边**）。

例如：先缩放，再旋转，再平移：
$$T \cdot R \cdot S \cdot \mathbf{x}$$

#### 3D 变换与透视投影(Perspective Projections)
- 3D 变换矩阵为 $4 \times 4$ 矩阵，形式与 2D 类似。
- **透视投影**：将 3D 点投影到 2D 屏幕（$xy$ 平面）。若视点在 $(0,0,d)$，则投影矩阵为：
$$P = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & -1/d & 1
\end{bmatrix}$$
  投影后需用齐次坐标归一化（除以第 4 个分量）得到实际 3D 坐标。



### 练习2.7 10
![2-34.png](picture/chapter_2_picture/2-34.png)



设 $D(\mathbf{x}) = s\mathbf{x}$（$s>0$），$R$ 为旋转矩阵，$T(\mathbf{x}) = \mathbf{x} + \mathbf{t}$。

- **$D$ 与 $R$**：  
  $D(R(\mathbf{x})) = s(R\mathbf{x}) = R(s\mathbf{x}) = R(D(\mathbf{x}))$，所以 **交换**。

- **$D$ 与 $T$**：  
  $D(T(\mathbf{x})) = s(\mathbf{x}+\mathbf{t}) = s\mathbf{x} + s\mathbf{t}$，  
  $T(D(\mathbf{x})) = s\mathbf{x} + \mathbf{t}$。  
  当 $s \neq 1$ 且 $\mathbf{t} \neq \mathbf{0}$ 时不相等，所以 **不交换**。

- **$R$ 与 $T$**：  
  $R(T(\mathbf{x})) = R\mathbf{x} + R\mathbf{t}$，  
  $T(R(\mathbf{x})) = R\mathbf{x} + \mathbf{t}$。  
  一般 $R\mathbf{t} \neq \mathbf{t}$（除非旋转角度为 $0$ 或 $2\pi$），所以 **不交换**。



### 练习2.7 11
![2-35.png](picture/chapter_2_picture/2-35.png)

给定两个 $3\times 3$ 齐次变换矩阵  
$$A_1 = \begin{bmatrix}
1 & 0 & 0 \\
\sin\varphi & \cos\varphi & 0 \\
0 & 0 & 1
\end{bmatrix}, \quad
A_2 = \begin{bmatrix}
\sec\varphi & -\tan\varphi & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}$$
证明 $A_2 A_1$ 是一个旋转矩阵。

计算乘积：
$$A_2 A_1 =
\begin{bmatrix}
\sec\varphi & -\tan\varphi & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
1 & 0 & 0 \\
\sin\varphi & \cos\varphi & 0 \\
0 & 0 & 1
\end{bmatrix}$$

逐项相乘：
- $(1,1)$：$\sec\varphi \cdot 1 + (-\tan\varphi)\sin\varphi = \sec\varphi - \tan\varphi \sin\varphi = \frac{1}{\cos\varphi} - \frac{\sin^2\varphi}{\cos\varphi} = \frac{1-\sin^2\varphi}{\cos\varphi} = \frac{\cos^2\varphi}{\cos\varphi} = \cos\varphi$
- $(1,2)$：$\sec\varphi \cdot 0 + (-\tan\varphi)\cos\varphi = -\frac{\sin\varphi}{\cos\varphi}\cos\varphi = -\sin\varphi$
- $(2,1)$：$0\cdot 1 + 1\cdot \sin\varphi = \sin\varphi$
- $(2,2)$：$0\cdot 0 + 1\cdot \cos\varphi = \cos\varphi$

所以：
$$A_2 A_1 =
\begin{bmatrix}
\cos\varphi & -\sin\varphi & 0 \\
\sin\varphi & \cos\varphi & 0 \\
0 & 0 & 1
\end{bmatrix}$$

这正是绕原点旋转 $\varphi$ 角的旋转矩阵（齐次坐标形式）。证毕。



### 练习2.7 13
![2-36.png](picture/chapter_2_picture/2-36.png)


**题目**：齐次变换矩阵 $M = \begin{bmatrix} A & \mathbf{p} \\ \mathbf{0}^T & 1 \end{bmatrix}$（$A$ 为 $2\times 2$，$\mathbf{p}\in\mathbb{R}^2$）等价于先线性变换再平移。证明。

**解**：

对任意 $\mathbf{x} = \begin{bmatrix} \mathbf{x}_2 \\ 1 \end{bmatrix}$（$\mathbf{x}_2\in\mathbb{R}^2$）：
$$M\mathbf{x} = \begin{bmatrix} A\mathbf{x}_2 + \mathbf{p} \\ 1 \end{bmatrix}$$

即先对 $\mathbf{x}_2$ 做线性变换 $A$，再平移 $\mathbf{p}$。

矩阵分解：
$$M = \begin{bmatrix} I & \mathbf{p} \\ 0 & 1 \end{bmatrix} \begin{bmatrix} A & \mathbf{0} \\ \mathbf{0}^T & 1 \end{bmatrix}$$

（先线性变换，后平移）。证毕。


### 练习2.7 14
![2-37.png](picture/chapter_2_picture/2-37.png)

习题 7 要求：绕点 $\mathbf{c} = (6, 8)$ 旋转 $60^\circ$。

旋转角 $\theta = 60^\circ$，绕原点旋转的矩阵为：
$$R = \begin{bmatrix}
\cos\theta & -\sin\theta \\
\sin\theta & \cos\theta
\end{bmatrix}
= \begin{bmatrix}
0.5 & -\frac{\sqrt{3}}{2} \\
\frac{\sqrt{3}}{2} & 0.5
\end{bmatrix}$$

在 2D 齐次坐标中，绕点 $\mathbf{c}$ 旋转 $\theta$ 的变换矩阵为：
$$M = \begin{bmatrix}
I & \mathbf{c} \\
\mathbf{0}^T & 1
\end{bmatrix}
\begin{bmatrix}
R & \mathbf{0} \\
\mathbf{0}^T & 1
\end{bmatrix}
\begin{bmatrix}
I & -\mathbf{c} \\
\mathbf{0}^T & 1
\end{bmatrix}$$

这对应于三步操作：
1. 平移 $-\mathbf{c}$（将点移到原点）
2. 绕原点旋转 $R$
3. 平移 $+\mathbf{c}$（移回原位）

计算 $M$：
$$M = \begin{bmatrix}
I & \mathbf{c} \\
0 & 1
\end{bmatrix}
\begin{bmatrix}
R & 0 \\
0 & 1
\end{bmatrix}
\begin{bmatrix}
I & -\mathbf{c} \\
0 & 1
\end{bmatrix}$$

$$M = \begin{bmatrix}
I & \mathbf{c} \\
0 & 1
\end{bmatrix}
\begin{bmatrix}
R & -R\mathbf{c} \\
0 & 1
\end{bmatrix}
=
\begin{bmatrix}
R & \mathbf{c} - R\mathbf{c} \\
0 & 1
\end{bmatrix}
=
\begin{bmatrix}
R & (I - R)\mathbf{c} \\
0 & 1
\end{bmatrix}$$

$M = \begin{bmatrix}
R & \mathbf{p} \\
0 & 1
\end{bmatrix}$，其中 $\mathbf{p} = (I - R)\mathbf{c}$。

这个矩阵的作用是：
$$\begin{bmatrix}
R & \mathbf{p} \\
0 & 1
\end{bmatrix}
\begin{bmatrix}
\mathbf{x} \\
1
\end{bmatrix}
=
\begin{bmatrix}
R\mathbf{x} + \mathbf{p} \\
1
\end{bmatrix}$$

即**先绕原点旋转 $R$，再平移 $\mathbf{p}$**。

求 $\mathbf{p}$
代入 $\mathbf{c} = (6, 8)$，$\cos60^\circ = 0.5$，$\sin60^\circ = \frac{\sqrt{3}}{2}$：

$$I - R = \begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}
-
\begin{bmatrix}
0.5 & -\frac{\sqrt{3}}{2} \\
\frac{\sqrt{3}}{2} & 0.5
\end{bmatrix}
=
\begin{bmatrix}
0.5 & \frac{\sqrt{3}}{2} \\
-\frac{\sqrt{3}}{2} & 0.5
\end{bmatrix}$$

因此：
$$\mathbf{p} = \begin{bmatrix}
0.5 & \frac{\sqrt{3}}{2} \\
-\frac{\sqrt{3}}{2} & 0.5
\end{bmatrix}
\begin{bmatrix}
6 \\ 8
\end{bmatrix}
= \begin{bmatrix}
0.5 \times 6 + \frac{\sqrt{3}}{2} \times 8 \\
-\frac{\sqrt{3}}{2} \times 6 + 0.5 \times 8
\end{bmatrix}
= \begin{bmatrix}
3 + 4\sqrt{3} \\
-3\sqrt{3} + 4
\end{bmatrix}$$

所以：
$$\boxed{\mathbf{p} = \begin{bmatrix}
3 + 4\sqrt{3} \\
4 - 3\sqrt{3}
\end{bmatrix}}$$

**结论**

习题 7 的变换等价于：
$$\boxed{
\text{绕原点旋转 } 60^\circ \quad \text{然后平移 } \mathbf{p} = \begin{bmatrix}
3 + 4\sqrt{3} \\
4 - 3\sqrt{3}
\end{bmatrix}
}$$

其 $3\times 3$ 齐次坐标矩阵为：
$$M = \begin{bmatrix}
0.5 & -\frac{\sqrt{3}}{2} & 3 + 4\sqrt{3} \\
\frac{\sqrt{3}}{2} & 0.5 & 4 - 3\sqrt{3} \\
0 & 0 & 1
\end{bmatrix}$$


### 练习2.7 16
![2-38.png](picture/chapter_2_picture/2-38.png)


齐次坐标 $(X,Y,Z,H)$（$H\neq 0$）表示点 $(X/H, Y/H, Z/H)$。

- 第一组：$(1/4, -2/4, 3/4) = (0.25, -0.5, 0.75)$
- 第二组：$(10/40, -20/40, 30/40) = (0.25, -0.5, 0.75)$

二者完全相同。第二组是第一组的 $10$ 倍，所以表示同一个点。


### 练习2.7 17
![2-39.png](picture/chapter_2_picture/2-39.png)
![2-40.png](picture/chapter_2_picture/2-40.png)

绕 $x$ 轴旋转 $\theta$ 的 $3\times 3$ 矩阵为：
$$R_x(\theta) = \begin{bmatrix}
1 & 0 & 0 \\
0 & \cos\theta & -\sin\theta \\
0 & \sin\theta & \cos\theta
\end{bmatrix}$$

齐次坐标下为：
$$M = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & \cos\theta & -\sin\theta & 0 \\
0 & \sin\theta & \cos\theta & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}$$

代入 $\theta = 60^\circ$，$\cos60^\circ = 0.5$，$\sin60^\circ = \sqrt{3}/2$：
$$\boxed{
M = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 0.5 & -\frac{\sqrt{3}}{2} & 0 \\
0 & \frac{\sqrt{3}}{2} & 0.5 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
}$$


### 练习2.7 19
![2-41.png](picture/chapter_2_picture/2-41.png)


透视投影矩阵（齐次坐标）为：
$$P = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & -\frac{1}{10} & 1
\end{bmatrix}$$

对每个顶点 $\mathbf{v} = (x,y,z)$，齐次坐标为 $(x,y,z,1)$，投影后得到 $(X,Y,0,H)$，其中 $H = 1 - z/10$，最后归一化为 $(X/H, Y/H, 0)$。

**顶点 1**：$(4.2, 1.2, 4)$  
$H = 1 - 4/10 = 0.6$，像点：$(4.2/0.6, 1.2/0.6, 0) = (7, 2, 0)$

**顶点 2**：$(6, 4, 2)$  
$H = 1 - 2/10 = 0.8$，像点：$(6/0.8, 4/0.8, 0) = (7.5, 5, 0)$

**顶点 3**：$(2, 2, 6)$  
$H = 1 - 6/10 = 0.4$，像点：$(2/0.4, 2/0.4, 0) = (5, 5, 0)$

投影后的三角形顶点为：
$$\boxed{(7,2,0),\ (7.5,5,0),\ (5,5,0)}$$



### 练习2.7 21
![2-42.png](picture/chapter_2_picture/2-42.png)

In [56]:
# 已知 CIE 到 RGB 的转换矩阵（从屏幕的 RGB 到 CIE XYZ）
M = np.array([
    [0.61, 0.29, 0.150],
    [0.35, 0.59, 0.063],
    [0.04, 0.12, 0.787]
])

# 计算逆矩阵，用于将 CIE XYZ 转换回 RGB
M_inv = np.linalg.inv(M)

print("M 的逆矩阵（CIE → RGB）：")
print(M_inv)
print()

# 验证：M_inv * M 应接近单位矩阵
print("验证 M_inv * M = I：")
print(np.round(M_inv @ M, decimals=10))
print()

# 示例：给出一组 CIE 数据 (X, Y, Z)，转换为 RGB
cie_example = np.array([0.5, 0.4, 0.3])  # 任意选取
rgb = M_inv @ cie_example

print(f"CIE 数据 ({cie_example[0]:.2f}, {cie_example[1]:.2f}, {cie_example[2]:.2f}) 转换为 RGB：")
print(f"R = {rgb[0]:.4f}, G = {rgb[1]:.4f}, B = {rgb[2]:.4f}")

# 为了验证，再转回 CIE
cie_back = M @ rgb
print("\n验证：将 RGB 转回 CIE：")
print(f"({cie_back[0]:.4f}, {cie_back[1]:.4f}, {cie_back[2]:.4f})")

M 的逆矩阵（CIE → RGB）：
[[ 2.25855419 -1.03950752 -0.34726068]
 [-1.34953521  2.34409612  0.06957081]
 [ 0.09098101 -0.30458861  1.27768987]]

验证 M_inv * M = I：
[[ 1. -0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]

CIE 数据 (0.50, 0.40, 0.30) 转换为 RGB：
R = 0.6093, G = 0.2837, B = 0.3070

验证：将 RGB 转回 CIE：
(0.5000, 0.4000, 0.3000)


### 练习2.7 21
![2-42.png](picture/chapter_2_picture/2-42.png)

In [57]:
# 定义从 RGB 到 YIQ 的转换矩阵
M = np.array([
    [0.299, 0.587, 0.114],
    [0.596, -0.275, -0.321],
    [0.212, -0.528, 0.311]
])

# 计算逆矩阵 M^{-1}（从 YIQ 转回 RGB 的显式转换矩阵）
M_inv = np.linalg.inv(M)

print("从 YIQ 转换到 RGB 的矩阵 (M^{-1})：")
print(M_inv)

# 给定一个示例 YIQ 信号
YIQ = np.array([0.5, 0.2, 0.1])

# 方法一：使用逆矩阵
# 根据 YIQ = M * RGB，两边左乘 M^{-1} 得 RGB = M^{-1} * YIQ
RGB_by_inv = M_inv @ YIQ

#  方法二：解线性方程组（避免显式求逆）
# 直接解 M * RGB = YIQ，利用 LU 分解
RGB_by_solve = np.linalg.solve(M, YIQ)

# 4. 打印结果对比
print("\n输入的 YIQ 数据：", YIQ)
print("\n方法一：使用逆矩阵 M^{-1} 相乘")
print(f"R = {RGB_by_inv[0]:.6f}, G = {RGB_by_inv[1]:.6f}, B = {RGB_by_inv[2]:.6f}")

print("\n方法二：直接解线性方程组 np.linalg.solve")
print(f"R = {RGB_by_solve[0]:.6f}, G = {RGB_by_solve[1]:.6f}, B = {RGB_by_solve[2]:.6f}")

# 验证两种方法的结果是否一致
print("\n两种方法的误差（Frobenius 范数）：", np.linalg.norm(RGB_by_inv - RGB_by_solve))


从 YIQ 转换到 RGB 的矩阵 (M^{-1})：
[[ 1.0030893   0.95484906  0.61785971]
 [ 0.99677606 -0.27070623 -0.64478833]
 [ 1.00849784 -1.11048518  1.69956753]]

输入的 YIQ 数据： [0.5 0.2 0.1]

方法一：使用逆矩阵 M^{-1} 相乘
R = 0.754300, G = 0.379768, B = 0.452109

方法二：直接解线性方程组 np.linalg.solve
R = 0.754300, G = 0.379768, B = 0.452109

两种方法的误差（Frobenius 范数）： 1.9229626863835638e-16


## 2.8 $\mathbb{R}^n$ 的子空间（Subspaces of $\mathbb{R}^n$）

#### 子空间的定义
集合 $H \subseteq \mathbb{R}^n$ 称为子空间，若满足：
1. **零向量** $\mathbf{0} \in H$
2. **加法封闭**：若 $\mathbf{u}, \mathbf{v} \in H$，则 $\mathbf{u} + \mathbf{v} \in H$
3. **数乘封闭**：若 $\mathbf{u} \in H$，$c$ 为任意标量，则 $c\mathbf{u} \in H$

**注**：过原点的直线或平面是子空间；不过原点的直线/平面则不是。

#### 列空间（Column Space, Col $A$）
$$ \mathrm{Col} A = \operatorname{Span}\{\mathbf{a}_1, \mathbf{a}_2, \ldots, \mathbf{a}_n\} $$
即矩阵 $A$ 的所有列的线性组合构成的集合。
- $\mathrm{Col} A$ 是 $\mathbb{R}^m$ 的子空间（$A$ 为 $m \times n$）。
- 向量 $\mathbf{b}$ 在 $\mathrm{Col} A$ 中 $\iff$ 方程 $A\mathbf{x} = \mathbf{b}$ 有解。

#### 零空间（Null Space, Nul $A$）
$$ \mathrm{Nul} A = \{\mathbf{x} \in \mathbb{R}^n : A\mathbf{x} = \mathbf{0}\} $$
即齐次方程 $A\mathbf{x} = \mathbf{0}$ 的所有解构成的集合。
- $\mathrm{Nul} A$ 是 $\mathbb{R}^n$ 的子空间（$A$ 为 $m \times n$）。

零空间是所有被矩阵 $A$ 乘完之后变成零向量$\mathbf{0}$ 的那些向量 $ \mathbf{x} $ 的集合。

零空间：看输入。

列空间：看输出。

#### 基（Basis）
一个集合 $\mathcal{B} = \{\mathbf{b}_1, \ldots, \mathbf{b}_p\} \subseteq H$ 是 $H$ 的基，若：
1. $\mathcal{B}$ 线性无关
2. $\operatorname{Span}\{\mathcal{B}\} = H$

#### 如何求基
- **列空间 Col $A$ 的基**：取 $A$ 的**主元列**（化为行阶梯形后，主元所在的原始列）。
- **零空间 Nul $A$ 的基**：解 $A\mathbf{x} = \mathbf{0}$，将通解写成参数向量形式（自由变量分别取 1 得到的向量）。

#### 核心性质（定理 12、13）
- $\mathrm{Nul} A$ 是 $\mathbb{R}^n$ 的子空间（定理 12）
- 矩阵 $A$ 的主元列构成 $\mathrm{Col} A$ 的一组基（定理 13）


对矩阵进行行变换（行化简），不会改变列向量之间的“线性关系”。

### 练习2.8 7
![2-44.png](picture/chapter_2_picture/2-44.png)


**a.**  

3 个（因为集合中只有这三个向量）。

**b.**  

Col $A$ 是 $\mathbb{R}^3$ 的一个子空间，由 $\mathbf{v}_1, \mathbf{v}_2, \mathbf{v}_3$ 张成。若这些列线性无关，则 Col $A$ 是 $\mathbb{R}^3$，包含无穷多个向量；若相关，则是一个低维子空间，仍然包含无穷多个向量（除非全为零向量）。因此 **Col $A$ 包含无穷多个向量**。

**c.**  

要判断 $\mathbf{p}$ 是否为 $\mathbf{v}_1, \mathbf{v}_2, \mathbf{v}_3$ 的线性组合，即解方程组 $A\mathbf{x} = \mathbf{p}$。

将增广矩阵 $[A \ \mathbf{p}]$ 行化简：
$$\begin{bmatrix}
2 & -3 & -4 & 6 \\
-8 & 8 & 6 & -10 \\
6 & -7 & -7 & 11
\end{bmatrix}
\sim
\begin{bmatrix}
1 & 0 & 0 & 1 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & -1
\end{bmatrix}$$

得到唯一解 $\mathbf{x} = (1, 0, -1)$，即 $\mathbf{p} = 1\cdot \mathbf{v}_1 + 0\cdot \mathbf{v}_2 + (-1)\cdot \mathbf{v}_3$。  
因此 **$\mathbf{p} \in \mathrm{Col} A$**。



### 练习2.8 9
![2-45.png](picture/chapter_2_picture/2-45.png)

判断 $\mathbf{p}$ 是否在 $\mathrm{Nul} A$，只需计算 $A\mathbf{p}$：

$$A\mathbf{p} = \begin{bmatrix}
2 & -3 & -4 \\
-8 & 8 & 6 \\
6 & -7 & -7
\end{bmatrix}
\begin{bmatrix}
6 \\ -10 \\ 11
\end{bmatrix}
= \begin{bmatrix}
2\cdot6 + (-3)(-10) + (-4)\cdot11 \\
-8\cdot6 + 8(-10) + 6\cdot11 \\
6\cdot6 + (-7)(-10) + (-7)\cdot11
\end{bmatrix}
= \begin{bmatrix}
12 + 30 - 44 \\
-48 - 80 + 66 \\
36 + 70 - 77
\end{bmatrix}
= \begin{bmatrix}
-2 \\
-62 \\
29
\end{bmatrix}
\neq \mathbf{0}$$

因此 $\mathbf{p} \notin \mathrm{Nul} A$。



### 练习2.8 43-44
![2-46.png](picture/chapter_2_picture/2-46.png)
#### 习题 43

**已知**：矩阵 $B$ 的 4 个列向量线性无关。
将 $B$ 按列分块，记作：
$$ B = [\mathbf{b}_1 \ \mathbf{b}_2 \ \mathbf{b}_3 \ \mathbf{b}_4] $$

设 $\mathbf{x}$ 是零空间 $\mathrm{Nul} B$ 中的任意一个向量，即：
$$ \mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{bmatrix} $$

根据零空间的定义，有：
$$ B\mathbf{x} = \mathbf{0} $$

将其展开为列向量的线性组合形式：
$$ x_1\mathbf{b}_1 + x_2\mathbf{b}_2 + x_3\mathbf{b}_3 + x_4\mathbf{b}_4 = \mathbf{0} $$

由于题目已知列向量 $\mathbf{b}_1, \mathbf{b}_2, \mathbf{b}_3, \mathbf{b}_4$ 是线性无关的，根据线性无关的等价定义：
> “若一组向量线性无关，则它们线性组合为零向量的**唯一方法**是所有系数全为零。”

因此，该方程只有零解：
$$ x_1 = 0,\quad x_2 = 0,\quad x_3 = 0,\quad x_4 = 0 $$

也就是说，满足 $B\mathbf{x} = \mathbf{0}$ 的唯一向量就是零向量本身。

**结论**
$$ \boxed{\mathrm{Nul} B = \{\mathbf{0}\}} $$

（即，该矩阵的零空间只包含零向量，维度为 0。这意味着齐次线性方程组 $B\mathbf{x} = \mathbf{0}$ 只有平凡解。）




#### 习题 44

设 $A$ 是一个 $m \times n$ 矩阵，即它有 $m$ 行、$n$ 列。

题目说它的列构成 $\mathbb{R}^m$ 的一组基。根据“基”的定义，它必须同时满足两个条件：

**由“张成（Span）”条件确定行数**
- 基向量必须属于目标空间 $\mathbb{R}^m$，所以每个列向量都必须是 $m$ 维的。
- 因此，矩阵的行数必然是 $m$。
- 另外，$n$ 个向量要张成一个 $m$ 维空间，**至少需要 $m$ 个向量** 。
- 所以得出：$\mathbf{n \ge m}$。

**由“线性无关（Linearly Independent）”条件确定列数**
- 在 $\mathbb{R}^m$ 这个空间里，一组线性无关的向量，**最多只能有 $m$ 个** 。
- 题目要求列向量线性无关，所以列数 $n$ 不能超过 $m$。
- 所以得出：$\mathbf{n \le m}$。


既有 $n \ge m$，又有 $n \le m$，两个条件同时成立，只能推出：
$$ n = m $$

**最终结论**
矩阵 $A$ 的行数等于列数，即 **$A$ 是一个 $m \times m$ 的方阵**。

并且，因为它的列是 $\mathbb{R}^m$ 的一组基，所以这组列向量既张成整个空间又线性无关，这意味着 $A$ 是**可逆矩阵（非奇异矩阵）**。



### 练习2.8 45-46
![2-47.png](picture/chapter_2_picture/2-47.png)

In [58]:
import sympy as sp

def analyze_matrix(A, name):
    """
    分析矩阵 A 的列空间和零空间
    """
    print(f"分析矩阵: {name}")
    print(f"矩阵大小: {A.shape[0]} x {A.shape[1]}")
    
    # 1. 求行最简形和主元列
    rref_matrix, pivot_cols = A.rref()
    print("\n1. 行最简形 (RREF)")
    sp.pprint(rref_matrix)
    print(f"主元列: {[i+1 for i in pivot_cols]}")
    
    # 2. 列空间 (Col A) 的基：取原矩阵的主元列
    print("\n2. 列空间 Col A 的基")
    basis_cols = [A[:, i] for i in pivot_cols]
    for i, col in zip(pivot_cols, basis_cols):
        print(f"\n第 {i+1} 列:")
        sp.pprint(col)
    
    # 3. 零空间 (Nul A) 的基：求解 Ax = 0
    print("\n3. 零空间 Nul A 的基 (解 Ax=0)")
    null_basis = A.nullspace()
    if not null_basis:
        print("零空间只包含零向量：Nul A = {0}")
    else:
        for idx, vec in enumerate(null_basis):
            print(f"\n基向量 {idx+1}:")
            sp.pprint(vec)
        

# 习题 45
A45 = sp.Matrix([
    [3, -5, 0, -1, 3],
    [-7, 9, -4, 9, -11],
    [-5, 7, -2, 5, -7],
    [3, -7, -3, 4, 0]
])

analyze_matrix(A45, "习题 45")

# 习题 46
A46 = sp.Matrix([
    [5, 2, 0, -8, -8],
    [4, 1, 2, -8, -9],
    [5, 1, 3, 5, 19],
    [-8, -5, 6, 8, 5]
])

analyze_matrix(A46, "习题 46")

分析矩阵: 习题 45
矩阵大小: 4 x 5

1. 行最简形 (RREF)
⎡1  0  5/2  -9/2  7/2⎤
⎢                    ⎥
⎢0  1  3/2  -5/2  3/2⎥
⎢                    ⎥
⎢0  0   0    0     0 ⎥
⎢                    ⎥
⎣0  0   0    0     0 ⎦
主元列: [1, 2]

2. 列空间 Col A 的基

第 1 列:
⎡3 ⎤
⎢  ⎥
⎢-7⎥
⎢  ⎥
⎢-5⎥
⎢  ⎥
⎣3 ⎦

第 2 列:
⎡-5⎤
⎢  ⎥
⎢9 ⎥
⎢  ⎥
⎢7 ⎥
⎢  ⎥
⎣-7⎦

3. 零空间 Nul A 的基 (解 Ax=0)

基向量 1:
⎡-5/2⎤
⎢    ⎥
⎢-3/2⎥
⎢    ⎥
⎢ 1  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎣ 0  ⎦

基向量 2:
⎡9/2⎤
⎢   ⎥
⎢5/2⎥
⎢   ⎥
⎢ 0 ⎥
⎢   ⎥
⎢ 1 ⎥
⎢   ⎥
⎣ 0 ⎦

基向量 3:
⎡-7/2⎤
⎢    ⎥
⎢-3/2⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎣ 1  ⎦
分析矩阵: 习题 46
矩阵大小: 4 x 5

1. 行最简形 (RREF)
⎡1  0  0   60   122 ⎤
⎢                   ⎥
⎢0  1  0  -154  -309⎥
⎢                   ⎥
⎢0  0  1  -47   -94 ⎥
⎢                   ⎥
⎣0  0  0   0     0  ⎦
主元列: [1, 2, 3]

2. 列空间 Col A 的基

第 1 列:
⎡5 ⎤
⎢  ⎥
⎢4 ⎥
⎢  ⎥
⎢5 ⎥
⎢  ⎥
⎣-8⎦

第 2 列:
⎡2 ⎤
⎢  ⎥
⎢1 ⎥
⎢  ⎥
⎢1 ⎥
⎢  ⎥
⎣-5⎦

第 3 列:
⎡0⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎢3⎥
⎢ ⎥
⎣6⎦

3. 零空间 Nul A 的基 (解 Ax=0)

基向量 1:
⎡-60⎤
⎢   ⎥
⎢154⎥
⎢   ⎥
⎢47 ⎥
⎢   ⎥
⎢ 1 ⎥
⎢   ⎥
⎣ 0 ⎦

基向量 2:
⎡-122⎤
⎢  

## 2.9 维数与秩（Dimension and Rank）

继续讨论子空间和子空间的基

#### 坐标向量（Coordinate Vector）
若 $\mathcal{B} = \{\mathbf{b}_1, \ldots, \mathbf{b}_p\}$ 是 $H$ 的一组基，且 $\mathbf{x} = c_1\mathbf{b}_1 + \cdots + c_p\mathbf{b}_p$，则 $\mathbf{x}$ 相对于 $\mathcal{B}$ 的坐标向量为：
$$[\mathbf{x}]_{\mathcal{B}} = \begin{bmatrix} c_1 \\ c_2 \\ \vdots \\ c_p \end{bmatrix}$$

相当于 $\mathbf{x}$ 这个向量在 $\mathcal{B}$ 这个空间里的坐标

![2-48.png](picture/chapter_2_picture/2-48.png)

坐标映射 $\mathbf{x} \mapsto [\mathbf{x}]_{\mathcal{B}}$ 是 $H$ 到 $\mathbb{R}^p$ 的一一对应（同构）。

同构（isomorphic）：粗略理解为换一个视角去看同一个东西。降维。

同 = 相同。

构 = 结构（这里指线性运算的规则，即加法和数乘）。

同构 = “线性结构完全相同”。
映射 “preserves linear combinations”（保持线性组合）

为什么要搞同构？

因为 $\mathbb{R}^p$ 是最简单的空间。
如果 $H$ 是一个 5 维的子空间（虽然它在 $\mathbb{R}^100$ 里），直接处理 100 个数太多了。

因为同构，我可以忽略它外面的 100 维壳子，只在它内部建立一个坐标系 $\mathcal{B}$。

这样，H里的所有复杂运算，都可以全数转换成 $\mathbb{R}^5$ 里的简单加减乘除。算完结果后，再通过坐标映射变回原空间。


#### 维数（Dimension）
$$\dim H = \text{基中向量的个数}$$
- 零子空间 $\{\mathbf{0}\}$ 的维数为 0。
- $\dim \mathbb{R}^n = n$
- 过原点的直线维度 1，平面维度 2。

#### 秩（Rank）
$$\operatorname{rank} A = \dim (\mathrm{Col} A) = \text{主元列的个数}$$

#### 秩定理（Theorem 14）
若 $A$ 有 $n$ 列，则：
$$\operatorname{rank} A + \dim (\mathrm{Nul} A) = n$$

> 即：主元列数 + 自由变量数 = 总列数



例：
设有一个 $ 3 \times 5 $ 矩阵（3 行 5 列），行化简后有 **2 个主元列**。
- **含义**：方程 $A\mathbf{x} = \mathbf{0}$ 的解中有 **3 个自由变量**（即零空间中有 3 个基向量）。

将矩阵 $A$ 视为一个从 $\mathbb{R}^5$ 到 $\mathbb{R}^3$ 的线性变换：
- **输入空间**：5 维（$\mathbb{R}^5$）
- **输出空间**：3 维（$\mathbb{R}^3$）

由于 $\operatorname{rank}(A) = 2$，说明：
- 输出空间（列空间）只占 $\mathbb{R}^3$ 中的一个 **2 维平面**（丢失了 1 个维度的信息）。
- 既然输出被“压扁”了 1 维，那么输入空间里必然有 **$5 - 2 = 3$ 个方向** 被完全映射成零向量（这些方向构成零空间）。

矩阵把 5 维输入压扁成 3 维输出里的一个平面，因此丢掉了 1 个输出维度，但在输入里，有 3 个方向被完全压成了零。



#### 基定理（Theorem 15）
若 $H$ 是 $p$ 维子空间，则：
- 任意 $p$ 个线性无关的向量自动构成 $H$ 的基
- 任意 $p$ 个张成 $H$ 的向量自动构成 $H$ 的基

#### 可逆矩阵定理（续，定理补充）
对于 $n \times n$ 方阵 $A$，以下命题等价于“$A$ 可逆”：
- **m.** $A$ 的列向量构成 $\mathbb{R}^n$ 的一组基
- **n.** $\mathrm{Col} A = \mathbb{R}^n$
- **o.** $\operatorname{rank} A = n$
- **p.** $\dim (\mathrm{Nul} A) = 0$
- **q.** $\mathrm{Nul} A = \{\mathbf{0}\}$


#### 总结对照表

| 概念 | 符号 | 含义 | 维数/求法 |
| :--- | :--- | :--- | :--- |
| 列空间 | $\mathrm{Col} A$ | 所有 $A\mathbf{x}$ 的集合 | 主元列数 = $\operatorname{rank} A$ |
| 零空间 | $\mathrm{Nul} A$ | 方程 $A\mathbf{x}=\mathbf{0}$ 的解集 | 自由变量个数 = $n - \operatorname{rank} A$ |
| 秩 | $\operatorname{rank} A$ | $\dim(\mathrm{Col} A)$ | 行阶梯形中主元个数 |
| 维数 | $\dim H$ | 基的向量个数 | - |
| 基 | Basis | 线性无关的张成集 | 主元列（Col）/ 参数向量（Nul） |

### 练习2.9 27
![2-49.png](picture/chapter_2_picture/2-49.png)

已知：
- 零空间 $\mathrm{Nul} A$ 的维数 = 3（因为有 3 个基向量）
- $A$ 是 $5 \times 7$ 矩阵，所以列数 $n = 7$

由秩定理（Theorem 14）：
$$\operatorname{rank} A + \dim(\mathrm{Nul} A) = n$$

代入已知：
$$\operatorname{rank} A + 3 = 7$$
$$\operatorname{rank} A = 4$$




### 练习2.9 29
![2-50.png](picture/chapter_2_picture/2-50.png)

已知：
- $\operatorname{rank} A = 4$
- $A$ 是 $7 \times 6$ 矩阵，所以列数 $n = 6$

由秩定理：
$$\operatorname{rank} A + \dim(\mathrm{Nul} A) = n$$

代入已知：
$$4 + \dim(\mathrm{Nul} A) = 6$$
$$\dim(\mathrm{Nul} A) = 2$$






### 练习2.9 35
![2-51.png](picture/chapter_2_picture/2-51.png)
## 习题 35

**题目**：设向量 $\mathbf{b}_1, \ldots, \mathbf{b}_p$ 张成子空间 $W$，令 $\{\mathbf{a}_1, \ldots, \mathbf{a}_q\}$ 是 $W$ 中任意一组含有超过 $p$ 个向量的集合。证明 $\{\mathbf{a}_1, \ldots, \mathbf{a}_q\}$ 必定线性相关。

令 $B = [\mathbf{b}_1 \cdots \mathbf{b}_p]$，$A = [\mathbf{a}_1 \cdots \mathbf{a}_q]$。

### 证明

a. 为什么对每个 $\mathbf{a}_j$，存在 $\mathbf{c}_j \in \mathbb{R}^p$ 使得 $\mathbf{a}_j = B\mathbf{c}_j$？

因为 $\{\mathbf{b}_1, \ldots, \mathbf{b}_p\}$ 张成 $W$，所以 $W$ 中的每一个向量都可以写成这组向量的线性组合。

特别地，对于每个 $\mathbf{a}_j \in W$，存在系数 $c_{1j}, c_{2j}, \ldots, c_{pj}$ 使得：
$$\mathbf{a}_j = c_{1j}\mathbf{b}_1 + c_{2j}\mathbf{b}_2 + \cdots + c_{pj}\mathbf{b}_p$$

令 $\mathbf{c}_j = \begin{bmatrix} c_{1j} \\ c_{2j} \\ \vdots \\ c_{pj} \end{bmatrix}$，则：
$$\mathbf{a}_j = B\mathbf{c}_j$$

b. 设 $C = [\mathbf{c}_1 \cdots \mathbf{c}_q]$，解释为什么存在非零向量 $\mathbf{u}$ 使得 $C\mathbf{u} = \mathbf{0}$。

$C$ 是一个 $p \times q$ 矩阵（$p$ 行，$q$ 列）。由于题设 $q > p$，即矩阵 $C$ 的列数多于行数，因此 $C$ 的列向量必定线性相关。

由线性相关性的等价条件，存在非零向量 $\mathbf{u} \in \mathbb{R}^q$ 使得：
$$C\mathbf{u} = \mathbf{0}$$

> **注**：这是线性代数的一个基本事实——当向量个数大于向量维数时，向量组必定线性相关。

c. 用 $B$ 和 $C$ 证明 $A\mathbf{u} = \mathbf{0}$，从而说明 $A$ 的列向量线性相关。

由 a 部分可知，对于每个 $j$，$\mathbf{a}_j = B\mathbf{c}_j$。将所有这些等式并列写成矩阵形式：
$$A = [\mathbf{a}_1 \ \mathbf{a}_2 \ \cdots \ \mathbf{a}_q] = [B\mathbf{c}_1 \ B\mathbf{c}_2 \ \cdots \ B\mathbf{c}_q] = BC$$

因此：
$$A\mathbf{u} = (BC)\mathbf{u} = B(C\mathbf{u}) = B(\mathbf{0}) = \mathbf{0}$$

由于 $\mathbf{u} \neq \mathbf{0}$，且 $A\mathbf{u} = \mathbf{0}$，根据线性相关性的定义，矩阵 $A$ 的列向量 $\{\mathbf{a}_1, \ldots, \mathbf{a}_q\}$ 线性相关。





### 练习2.9 36
![2-52.png](picture/chapter_2_picture/2-52.png)

### 证明

设基 $B$ 中有 $p$ 个向量，基 $A$ 中有 $q$ 个向量。

- 因为 $B$ 是基，所以 $B$ 张成 $W$（且线性无关）。
- 因为 $A$ 也是 $W$ 中的一组基，所以 $A$ 中的 $q$ 个向量都在 $W$ 中。

假设 $q > p$（即 $A$ 包含多于 $B$ 的向量）。
- 由习题 35，若一个向量组（$A$）含有超过 $p$ 个向量，且这些向量都在 $W$ 中（而 $W$ 由 $p$ 个向量 $B$ 张成），则 $A$ 必定线性相关。
- 但 $A$ 是基，必须线性无关，矛盾。

所以假设不成立，$q \le p$。即 $A$ 中向量数不能多于 $B$ 中向量数。

反之，假设 $p > q$（即 $B$ 包含多于 $A$ 的向量）。

由于 $A$ 张成 $W$，而 $B$ 含有超过 $q$ 个向量，由习题 35，$B$ 必定线性相关。
但 $B$ 是基，必须线性无关，矛盾。

所以假设不成立，$p \le q$。

**结论**：$p \le q$ 且 $q \le p$，因此 $p = q$。



### 练习2.9 37
![2-53.png](picture/chapter_2_picture/2-53.png)

In [59]:
v1 = np.array([12, -4, 9, 5])
v2 = np.array([15, -7, 12, 8])
x = np.array([19, -11, 16, 12])

# 构造矩阵 A = [v1 v2]
A37 = np.column_stack((v1, v2))

# 检查 v1, v2 是否线性无关（即秩是否为2）
rank_A = np.linalg.matrix_rank(A37)
print(f"v1, v2 的秩 = {rank_A}")

# 求解 A c = x （超定方程组，使用最小二乘）
c, residuals, rank, s = np.linalg.lstsq(A37, x, rcond=None)

# 检查残差是否接近0，判断 x 是否在列空间中
if np.allclose(residuals, 0) and rank_A == 2:
    print("x 在 H 中")
    print(f"B-坐标向量 [x]_B = ({c[0]:.6f}, {c[1]:.6f})")
else:
    print("x 不在 H 中")


v1, v2 的秩 = 2
x 在 H 中
B-坐标向量 [x]_B = (-1.333333, 2.333333)


### 练习2.9 38
![2-54.png](picture/chapter_2_picture/2-54.png)

In [60]:
v1 = np.array([-5, 4, -3, 2])
v2 = np.array([7, -5, 3, -3])
v3 = np.array([-8, 6, -4, 3])
x = np.array([-7, 8, -9, 1])

# 构造矩阵 A = [v1 v2 v3]
A38 = np.column_stack((v1, v2, v3))
rank_A38 = np.linalg.matrix_rank(A38)
print(f"v1, v2, v3 的秩 = {rank_A38}")

# 求解 A c = x
c, residuals, rank, s = np.linalg.lstsq(A38, x, rcond=None)

if np.allclose(residuals, 0) and rank_A38 == 3:
    print("x 在 H 中")
    print(f"B-坐标向量 [x]_B = ({c[0]:.6f}, {c[1]:.6f}, {c[2]:.6f})")
else:
    print("x 不在 H 中（或 B 不是基）")

v1, v2, v3 的秩 = 3
x 在 H 中
B-坐标向量 [x]_B = (5.000000, 6.000000, 3.000000)


### Supplementary exercises 20
![2-55.png](picture/chapter_2_picture/2-55.png)
$$A = \begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix}, \qquad B = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}$$

 证明 $A^2 = I$

$$A^2 = A \cdot A = \begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix} \begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix}
= \begin{bmatrix} 1\cdot1 + 0\cdot0 & 1\cdot0 + 0\cdot(-1) \\ 0\cdot1 + (-1)\cdot0 & 0\cdot0 + (-1)\cdot(-1) \end{bmatrix}
= \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} = I$$

成立。

证明 $B^2 = I$

$$B^2 = B \cdot B = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix} \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}
= \begin{bmatrix} 0\cdot0 + 1\cdot1 & 0\cdot1 + 1\cdot0 \\ 1\cdot0 + 0\cdot1 & 1\cdot1 + 0\cdot0 \end{bmatrix}
= \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} = I$$

成立。



证明 $AB = -BA$

先计算 $AB$：

$$AB = \begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix} \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}
= \begin{bmatrix} 1\cdot0 + 0\cdot1 & 1\cdot1 + 0\cdot0 \\ 0\cdot0 + (-1)\cdot1 & 0\cdot1 + (-1)\cdot0 \end{bmatrix}
= \begin{bmatrix} 0 & 1 \\ -1 & 0 \end{bmatrix}$$

再计算 $BA$：

$$BA = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix} \begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix}
= \begin{bmatrix} 0\cdot1 + 1\cdot0 & 0\cdot0 + 1\cdot(-1) \\ 1\cdot1 + 0\cdot0 & 1\cdot0 + 0\cdot(-1) \end{bmatrix}
= \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}$$

观察发现：

$$-BA = - \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}
= \begin{bmatrix} 0 & 1 \\ -1 & 0 \end{bmatrix} = AB$$

因此：

$$\boxed{AB = -BA}$$

矩阵 $A$ 和 $B$ 满足 **反对易关系（anticommute）**。



### 矩阵可逆判据（Invertible Matrix Criteria）

对于 **$n \times n$ 方阵 $A$**，下列所有命题等价。


#### 1. 代数运算（Algebraic）
| 判据 | 说明 |
| :--- | :--- |
| 存在逆矩阵 | 存在矩阵 $A^{-1}$，使得 $AA^{-1} = A^{-1}A = I$ |
| 左右逆等价 | 存在 $C$ 使 $CA = I$（左逆）或 $AD = I$（右逆），则 $A$ 必可逆 |
| 乘积可逆 | 若 $A$ 和 $B$ 可逆，则 $AB$ 可逆，且 $(AB)^{-1}=B^{-1}A^{-1}$ |
| 转置可逆 | $A^T$ 也可逆，且 $(A^T)^{-1} = (A^{-1})^T$ |


#### 2. 线性方程组（Linear Equations）
| 判据 | 说明 |
| :--- | :--- |
| 齐次方程只有零解 | $A\mathbf{x} = \mathbf{0}$ 仅有平凡解 $\mathbf{x} = \mathbf{0}$ |
| 非齐次方程总有唯一解 | 对 **任意** $\mathbf{b} \in \mathbb{R}^n$，方程 $A\mathbf{x} = \mathbf{b}$ 有唯一解（至少有一个解 ⇒ 自动唯一） |


#### 3. 行化简与主元（Row Reduction & Pivots）
| 判据 | 说明 |
| :--- | :--- |
| 行等价于单位矩阵 | $A$ 可通过初等行变换化为 $I_n$（即 $A \sim I_n$） |
| 满主元 | $A$ 有 $n$ 个主元位置（每个主对角线位置都有主元） |
| 行最简形 | $A$ 的行最简形（RREF）是 $I_n$ |


#### 4. 列空间、秩与零空间（Columns, Rank & Null Space）
| 判据 | 说明 |
| :--- | :--- |
| 列向量线性无关 | $A$ 的 $n$ 列构成线性无关组 |
| 列向量张成 $\mathbb{R}^n$ | $\operatorname{Col} A = \mathbb{R}^n$（列空间填满整个输出空间） |
| 列向量形成基 | 列向量是 $\mathbb{R}^n$ 的一组基（既无关又张成） |
| 满秩 | $\operatorname{rank}(A) = n$（主元数 = 列数 = 行数） |
| 零空间只有零向量 | $\operatorname{Nul} A = \{\mathbf{0}\}$，即 $\dim(\operatorname{Nul} A) = 0$ |


#### 5. 线性变换（Linear Transformations）
设 $T(\mathbf{x}) = A\mathbf{x}$，则：
| 判据 | 说明 |
| :--- | :--- |
| 单射（One-to-one） | 不同输入映射到不同输出（$T(\mathbf{x})=T(\mathbf{y}) \Rightarrow \mathbf{x}=\mathbf{y}$） |
| 满射（Onto） | 输出空间 $\mathbb{R}^n$ 中每个向量都有原像 |
| 双射（可逆变换） | 既是单射又是满射，存在逆变换 $T^{-1}$ |


#### 6. 行列式（Determinant）—— 常用快速判据
| 判据 | 说明 |
| :--- | :--- |
| 行列式非零 | $\det(A) \neq 0$ |

